/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Master Subscription
 * Agreement ("License") which can be viewed at
 * http://www.sugarcrm.com/crm/master-subscription-agreement
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *  (i) the "Powered by SugarCRM" logo and
 *  (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2012 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/
SUGAR.kb=function(){var tree;var configureDlg;var firstClick=true;var modalMoveDocsDialog;var tagsTreeModalMoveDocs;var modalMoveDocsDialog='';var applyTagsToDocs='';var previousSearchFoundTags=new Array();var previousNodesCount=0;var myDialog;var clickedNode='';var clickedNodeMove='';var checkedNodeApply='';var FAQ_TAG_NOT_RENAME_MESSAGE=SUGAR.language.get('KBDocuments','LBL_FAQ_TAG_NOT_RENAME_MESSAGE');var ROOT_TAG=SUGAR.language.get('KBTags','LBL_TAGS_ROOT_LABEL');return{displayNodeMessage:function(){},getLocalizedLabels:function(moduleOrAppList,msg){return SUGAR.language.get(moduleOrAppList,msg);},displayNodeMessage:function(){document.getElementById('CreateNodeMessage').style.display='';document.getElementById('CreateNodeMessage').innerHTML='Please select a node';},hideMove:function(){document.getElementById('CreateNodeMove').style.display='';document.getElementById('CreateNodeMove').innerHTML='<b><font COLOR=red>'+SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_A_TAG_FROM_TREE')+'</b>';var tagsTree=YAHOO.widget.TreeView.trees['tagstreeMoveDocsModal'];document.getElementById('Move').style.visibility="hidden";document.getElementById('Cancel_Move').style.visibility="hidden";if(clickedNodeMove.data==undefined){}
else{clickedNodeMove.getLabelEl().style.backgroundColor="white";}},hideApply:function(){document.getElementById('CreateNodeApply').style.display='';document.getElementById('CreateNodeApply').innerHTML='<b><font COLOR=red>'+SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_TAGS_FROM_TREE')+'</b>';var selectedApplyTags=document.getElementsByName('selected_apply_tags[]');for(i=0;i<selectedApplyTags.length;i++){if(selectedApplyTags[i].checked){selectedApplyTags[i].checked=false;}}
document.getElementById('Apply').style.visibility="hidden";document.getElementById('Cancel_Apply').style.visibility="hidden";},displayNewNodeBody:function(){document.getElementById('searchAndCreate').style.display='none';document.getElementById('tag_new').disabled=false;document.getElementById('Ok').disabled=false;var tagsTree=YAHOO.widget.TreeView.trees['tagstree'];var root=tagsTree.getRoot();if(root!=null&&root.children.length>0){document.getElementById('CreateNodeMessage').style.display='';myDialog.setHeader(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_CREATING_NEW_TAG'));}
else{document.getElementById('tag_base').checked=true;document.getElementById('tag_base').disabled=true;}
document.getElementById('CancelDup').style.visibility="visible";},displayNewNodeBodyAdmin:function(){document.getElementById('CreateNode').style.display='';document.getElementById('tag_base').checked=true;document.getElementById('tagsCreate').style.display='';document.getElementById('tag_new').disabled=false;document.getElementById('Ok').disabled=false;var tagsTree=YAHOO.widget.TreeView.trees['tagstree'];var root=tagsTree.getRoot();if(root!=null&&root.children.length>0){document.getElementById('CreateNodeMessage').style.display='';document.getElementById('CreateNodeMessage').innerHTML='Please select a node';document.getElementById('CreateNode').style.display='';document.getElementById('tag_base').checked=true;document.getElementById('tagsCreate').style.display='';document.getElementById('tag_new').style.visibility="hidden";document.getElementById('Ok').style.visibility="hidden";document.getElementById('tag_base').checked=false;document.getElementById('tag_base').disabled=false;}
else{document.getElementById('tag_base').checked=true;document.getElementById('tag_base').disabled=true;}
document.getElementById('Cancel').style.visibility="visible";},hideMessageAndNodeAdmin:function(){document.getElementById('tag_selected_id').value='';document.getElementById('tag_selected').value='';document.getElementById('tag_new').value='';document.getElementById('tags_search').value='';document.getElementById('CreateNodeMessage').style.display='none';document.getElementById('CreateNode').style.display='none';if(previousSearchFoundTags!=null&&previousSearchFoundTags.length>0){for(i=0;i<previousSearchFoundTags.length;i++){if(previousSearchFoundTags[i].getLabelEl().style.backgroundColor!="white"){previousSearchFoundTags[i].getLabelEl().style.backgroundColor="white";}}}
if(clickedNode.data==undefined){}
else{clickedNode.getLabelEl().style.backgroundColor="white";}},rootChecked:function(){if(document.getElementById('tag_base').checked==false){document.getElementById('CreateNodeMessage').style.display='';document.getElementById('CreateNodeMessage').innerHTML='Please select a node';document.getElementById('tag_new').disabled=true;document.getElementById('tag_selected_id').value='';document.getElementById('Ok').disabled=true;document.getElementById('tag_new').style.visibility="hidden";document.getElementById('Ok').style.visibility="hidden";}
else{document.getElementById('CreateNodeMessage').style.display='none';document.getElementById('tag_new').style.visibility="visible";document.getElementById('Ok').style.visibility="visible";}},hideMessageAndNode:function(){document.getElementById('tag_selected_id').value='';document.getElementById('tag_new').value='';document.getElementById('tags_search').value='';document.getElementById('CreateNodeMessage').style.display='none';document.getElementById('tagsCreate').style.display='none';if(myDialog!=null){myDialog.setHeader('Tags');}
document.getElementById('searchAndCreate').style.display='';if(previousSearchFoundTags!=null&&previousSearchFoundTags.length>0){for(i=0;i<previousSearchFoundTags.length;i++){if(previousSearchFoundTags[i].getLabelEl().style.backgroundColor!="white"){previousSearchFoundTags[i].getLabelEl().style.backgroundColor="white";}}}
if(clickedNode.data==undefined){}
else{clickedNode.getLabelEl().style.backgroundColor="white";}},moveTags:function(){var els=document.getElementsByName('selected_tags[]');var selected=false;for(i=0;i<els.length;i++){if(els[i].checked==true){els[i].value;selected=true;}}
if(!selected){alert('Select tags to be moved');}
else{var fRet;fRet=confirm('Would you select target tag after clicking ok or cancel');alert(fRet);}},applyTags:function(){var els=document.getElementsByName('selected_tags[]');var selected=false;for(i=0;i<els.length;i++){if(els[i].checked==true){els[i].value;selected=true;}}
if(!selected){alert('Select tags to be moved');}
else{var fRet;fRet=confirm('Would you select target tag after clicking ok or cancel');alert(fRet);}},dummyClick:function(){},cascadeTags:function(){var els=document.getElementsByName('selected_tags[]');var selected=false;var selectedTagId='';alert(firstClick);if(firstClick){for(i=0;i<els.length;i++){if(els[i].checked==true){selectedTagId=els[i].value;selected=true;break;}}
var tagsTree=YAHOO.widget.TreeView.trees['tagstree'];for(i=0;i<tagsTree._nodes.length;i++){if(tagsTree.getNodeByIndex(i)!=null){if(tagsTree.getNodeByIndex(i).data.id==selectedTagId){alert('node found '+tagsTree.getNodeByIndex(i).data.label);}}}}
else{alert(node.data.label);}
var elm=document.getElementsByName('selected_tags[]');if(selectedTagId!='undefined'&&selectedTagId!=null&&selectedTagId.length>0){for(i=0;i<elm.length;i++){elm[i].checked=true;}}},moveToTag:function(){var node=YAHOO.namespace('tagstree').selectednode;document.getElementById('tag_selected_move_from_id').value=node.data.id;},checkTags:function(){},checkChildTags:function(Node,nodeState){if(nodeState){Node.expand();}
else{Node.collapse();}
if(Node!=null&&Node.children.length>0){for(i=0;i<Node.children.length;i++){var childNodeBox=document.getElementById(Node.children[i].data.id);var childNode=Node.children[i];childNodeBox.checked=nodeState;if(childNode!=null&&childNode.children.length>0){checkChildTags(childNode,nodeState);}}}},deleteTags:function(){var els=document.getElementsByName('selected_tags[]');var selected=false;var selectedTagIds=new Array();var j=0;for(i=0;i<els.length;i++){if(els[i].checked==true){selectedTagIds[j]=els[i].value;selected=true;j++;}}
if(!selected){alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_TAGS_TO_DELETE'));return false;}
else{var callback={success:function(r){SUGAR.util.evalScript(r.responseText);}}
if(!confirm(SUGAR.language.get('app_strings','NTC_DELETE_CONFIRMATION'))){return false;}
postData='selectedTagIds='+YAHOO.lang.JSON.stringify(selectedTagIds)+'&module=KBTags&action=DeleteSelectedTags&to_pdf=1';YAHOO.util.Connect.asyncRequest('POST','index.php',callback,postData);}},selectArticles:function(action){save_kb_checks(0);if(document.KBAdminView.uid.value!=''){selectedArticleIds=document.KBAdminView.uid.value.split(',');selected=true;}else{selected=false;}
if(!selected){if(action=='Move'){alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_ARTICLES_TO_BE_MOVED_TO_OTHER_TAG'));}
if(action=='Apply'){alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_ARTICLES_TO_APPLY_TAGS'));}
if(action=='Delete'){alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_ARTICLES_TO_DELETE'));}
return false;}
return true;},deleteArticles:function(){save_kb_checks(0);if(document.KBAdminView.uid.value!=''){selectedArticleIds=document.KBAdminView.uid.value.split(',');selected=true;}else{selected=false;}
if(!selected){alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_ARTICLES_TO_DELETE'));return false;}
else{ajaxStatus.showStatus('DELETING_ARTICLES');window.setTimeout('ajaxStatus.hideStatus()',500);var callback={success:function(r){if(!confirm(SUGAR.language.get('app_strings','NTC_DELETE_CONFIRMATION'))){return false;}
if(r.responseText==1){alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_TAG_ALREADY_EXISTS'));}
else{SUGAR.util.evalScript(r.responseText);}}}
postData='selectedArticles='+YAHOO.lang.JSON.stringify(selectedArticleIds)+'&module=KBDocuments&action=DeleteSelectedArticles&to_pdf=1';YAHOO.util.Connect.asyncRequest('POST','index.php',callback,postData);}},modalMoveDocs:function(){document.getElementById('moveDlg').style.display='';var handleCancel=function(){this.cancel();}
var handleSubmit=function(){tree=new YAHOO.widget.TreeView('tagstreeMoveDocsModal');document.getElementById('moveDlg').style.display='';var attId=document.createElement('input');attId.setAttribute('id','t1');attId.setAttribute('name','t1');attId.setAttribute('tabindex','120');attId.setAttribute('type','text');attId.setAttribute('disabled',true);attId.setAttribute('value',tree.getNodeByIndex(1));linked_tags.appendChild(attId);this.submit();}
var myButtons=[];ajaxStatus.showStatus(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_LAUNCHING_TAG_BROWSING'));tagsTreeModalMoveDocs=new YAHOO.widget.SimpleDialog('moveDlg',{width:"500",fixedcenter:true,visible:true,draggable:false,close:true,modal:true});clickedNodeMove='';var moveTags='Move Tags';fillInTags=function(data){try{eval(data.responseText);}
catch(e){result=new Array();result['body']=SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_THERE_WAS_AN_ERROR_HANDLING_TAGS');}
tagsTreeModalMoveDocs.setBody(result['body']);tagsTreeModalMoveDocs.setHeader(' Tags');var listeners=new YAHOO.util.KeyListener(document,{keys:27},{fn:function(){this.hide();},scope:tree,correctScope:true});tagsTreeModalMoveDocs.cfg.queueProperty("keylisteners",listeners);tagsTreeModalMoveDocs.render(document.body);tagsTreeModalMoveDocs.show();tagsTreeModalMoveDocs.configFixedCenter(null,false);SUGAR.util.evalScript(result['body']);window.setTimeout('ajaxStatus.hideStatus()',1000);}
postData='tagsMode='+YAHOO.lang.JSON.stringify(moveTags)+'&module=KBTags&action=SelectCreateApplyAndMoveTags&to_pdf=1';YAHOO.util.Connect.asyncRequest('POST','index.php',{success:fillInTags,failure:fillInTags},postData);},applyTagsModal:function(){document.getElementById('applyDlg').style.display='';var handleCancel=function(){this.cancel();}
var handleSubmit=function(){tree=new YAHOO.widget.TreeView('tagstreeApplyTags');document.getElementById('applyDlg').style.display='';var attId=document.createElement('input');attId.setAttribute('id','t1');attId.setAttribute('name','t1');attId.setAttribute('tabindex','120');attId.setAttribute('type','text');attId.setAttribute('disabled',true);attId.setAttribute('value',tree.getNodeByIndex(1));linked_tags.appendChild(attId);this.submit();}
var myButtons=[];ajaxStatus.showStatus(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_LAUNCHING_TAG_BROWSING'));applyTagsToDocs=new YAHOO.widget.SimpleDialog('applyDlg',{width:"500",fixedcenter:true,visible:true,draggable:false,close:true,modal:true});var applyTags='Apply Tags';fillInTags=function(data){try{eval(data.responseText);}
catch(e){result=new Array();result['body']='There was an error handling this request.';}
applyTagsToDocs.setBody(result['body']);applyTagsToDocs.setHeader(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_HEAD_TAGS'));var listeners=new YAHOO.util.KeyListener(document,{keys:27},{fn:function(){this.hide();},scope:tree,correctScope:true});applyTagsToDocs.cfg.queueProperty("keylisteners",listeners);applyTagsToDocs.render(document.body);applyTagsToDocs.show();applyTagsToDocs.configFixedCenter(null,false);SUGAR.util.evalScript(result['body']);window.setTimeout('ajaxStatus.hideStatus()',1000);}
postData='tagsMode='+YAHOO.lang.JSON.stringify(applyTags)+'&module=KBTags&action=SelectCreateApplyAndMoveTags&to_pdf=1';YAHOO.util.Connect.asyncRequest('POST','index.php',{success:fillInTags,failure:fillInTags},postData);},serachTagAjax:function(){var searchTag=document.getElementById('tags_search').value;searchTag=searchTag.toLowerCase();if(searchTag!=null&&searchTag.length>0){var callback={success:function(r){SUGAR.util.evalScript(r.responseText);document.getElementById('tags_search').value=newTag;searchTree(false);document.getElementById('tags_search').value='';}}
postData='searchTagName='+YAHOO.lang.JSON.stringify(searchTag)+'&module=KBTags&action=SearchTags&to_pdf=1';YAHOO.util.Connect.asyncRequest('POST','index.php',callback,postData);}else{alert('Please type in the search field');}},moveDocsAndModalClose:function(){tree=new YAHOO.widget.TreeView('tagstreeMoveDocsModal');var node=YAHOO.namespace('tagstreeMoveDocsModal').selectednode;var tagId=node.data.id;if(tagId==document.getElementById('tag_selected_move_from_id').value){alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SOURCE_AND_TARGET_TAGS_ARE_SAME'));}
var selected=false;var selectedArticleIds=new Array();selectedArticleIds[0]=document.getElementById('tag_selected_move_from_id').value;selectedArticleIds[1]=tagId;var j=2;if(document.KBAdminView.uid.value!=''){els=document.KBAdminView.uid.value.split(',');for(x in els){selectedArticleIds[j]=els[x];j++;}
selected=true;}
var callback={success:function(r){SUGAR.util.evalScript(r.responseText);}}
postData='tagAndArticleIds='+YAHOO.lang.JSON.stringify(selectedArticleIds)+'&module=KBTags&action=MoveArticlesToTagsModal&to_pdf=1';YAHOO.util.Connect.asyncRequest('POST','index.php',callback,postData);document.getElementById('Move').style.visibility="hidden";document.getElementById('Cancel_Move').style.visibility="hidden";document.getElementById('CreateNodeMove').innerHTML='<b><font COLOR=red>'+SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_A_TAG_FROM_TREE')+'</b>';document.getElementById('selected_directory_children').innerHTML='';tagsTreeModalMoveDocs.submit();},applyTagsAndmodalClose:function(){tree=new YAHOO.widget.TreeView('tagstreeApplyTags');var selected=false;var selectedTagsArticlesIds=new Array();var tagsEls=document.getElementsByName('selected_apply_tags[]');var j=2;var countTags=0;for(i=0;i<tagsEls.length;i++){if(tagsEls[i].checked==true){selectedTagsArticlesIds[j]=tagsEls[i].value;j++;countTags++;}}
selectedTagsArticlesIds[0]=countTags;countArticles=0;if(document.KBAdminView.uid.value!=''){var els=document.KBAdminView.uid.value.split(',');for(x in els){selectedTagsArticlesIds[j]=els[x];j++;countArticles++;}
selected=true;}
selectedTagsArticlesIds[1]=countArticles;var callback={success:function(r){SUGAR.util.evalScript(r.responseText);}}
postData='tagAndArticleIds='+YAHOO.lang.JSON.stringify(selectedTagsArticlesIds)+'&module=KBTags&action=ApplyTagsToArticlesModal&to_pdf=1';YAHOO.util.Connect.asyncRequest('POST','index.php',callback,postData);document.getElementById('Apply').style.visibility="hidden";document.getElementById('Cancel_Apply').style.visibility="hidden";document.getElementById('CreateNodeApply').innerHTML='<b><font COLOR=red>'+SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_TAGS_FROM_TREE')+'</b>';applyTagsToDocs.submit();},addDocTags:function(form_name){var theForm=document.getElementById(form_name);var tagDiv=document.getElementById("Linked_Tags");var elems=theForm.getElementsByTagName("input");var elems1=tagDiv.getElementsByTagName("input");for(var i=0;i<elems1.length;i++){var el=elems1[i];if(el.id=='docTagIds[]'){theForm.appendChild(el);}}
for(var i=0;i<elems.length;i++){var el=elems[i];if(el.id=='docTagIds[]'){theForm.appendChild(el);}
if(el.id.indexOf('docTagIds')>=0||el.id=='docTagIds[]'){theForm.appendChild(el);}}},addNewNode:function(admin){var tagsTree=YAHOO.widget.TreeView.trees['tagstree'];var root=tagsTree.getRoot();var parent_tag_id='';if(!(document.getElementById('tag_selected_id').value=='')&&(document.getElementById('tag_selected_id').value.length>0)){parent_tag_id=document.getElementById('tag_selected_id').value;}
var newTag=document.getElementById('tag_new').value;if(newTag!=null&&newTag.length>0){var nodeChildExists=false;if(!nodeChildExists){ajaxStatus.showStatus(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SAVING_THE_TAG'));if(admin==null||admin=='undefined'){admin=false;}
var idName=new Array(3);idName[0]=newTag;idName[1]=parent_tag_id;if(admin){idName[2]=1;}
else{idName[2]=0;}
var treeDiv=document.getElementById('tagstree');window.setTimeout('ajaxStatus.hideStatus()',500);var callback={success:function(r){if(r.responseText==1){alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_TAG_ALREADY_EXISTS'));}
else{SUGAR.util.evalScript(r.responseText);}}}
postData=SUGAR.util.paramsToUrl({newTagName:YAHOO.lang.JSON.stringify(idName),module:"KBTags",action:"SaveTagsModal"});postData+="to_pdf=1";YAHOO.util.Connect.asyncRequest('GET','index.php?'+postData,callback);if(admin){document.getElementById('tag_new').value='';}
else{document.getElementById('tags_search').value=newTag;SUGAR.kb.searchTree(false);document.getElementById('tags_search').value='';SUGAR.kb.hideMessageAndNode();}
previousNodesCount=YAHOO.widget.TreeView.trees['tagstree']._nodes.length;previousSearchFoundTags=new Array();clickedNode='';}
else{alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_TAG_ALREADY_EXISTS'));}}
else{alert(SUGAR.language.get('KBDocuments','LBL_TYPE_NEW_NODE_NAME'));}},searchTree:function(admin){var searchTag=document.getElementById('tags_search').value;searchTag=searchTag.toLowerCase();if(searchTag!=null&&searchTag.length>0){var tagsTree=YAHOO.widget.TreeView.trees['tagstree'];var nodesCount=tagsTree._nodes.length;var startTagCount=0;if(previousNodesCount!=null&&previousNodesCount>0){startTagCount=previousNodesCount+2;}
else{startTagCount=1;}
var tagsCount=0;var currSearchFoundTags=new Array();if(previousSearchFoundTags!=null&&previousSearchFoundTags.length>0){for(i=0;i<previousSearchFoundTags.length;i++){if(previousSearchFoundTags[i].getLabelEl()!=null){if(previousSearchFoundTags[i].getLabelEl().style.backgroundColor!="white"){previousSearchFoundTags[i].getLabelEl().style.backgroundColor="white";}}}}
var treeCollapsed=false;for(i=startTagCount;i<nodesCount;i++){if(tagsTree.getNodeByIndex(i)!=null){var nodeLabel=tagsTree.getNodeByIndex(i).label;nodeLabel=nodeLabel.toLowerCase();if(admin){nodeLabel=nodeLabel.substring(nodeLabel.lastIndexOf('>')+1,nodeLabel.lastIndexOf('('));}
else{nodeLabel=nodeLabel.substring(0,nodeLabel.indexOf('('));}
if(searchTag==nodeLabel&&!treeCollapsed){tagsTree.collapseAll();treeCollapsed=true;}
if(searchTag==nodeLabel){currSearchFoundTags[tagsCount]=tagsTree.getNodeByIndex(i);tagsCount++;if(tagsTree.getNodeByIndex(i).parent!='RootNode'){var parentNode=tagsTree.getNodeByIndex(i).parent;var parentNodeBeforeRoot='';while(parentNode!=null&&parentNode!='RootNode'){if(parentNode.parent!=null&&parentNode.parent.expanded){parentNodeBeforeRoot=parentNode;break;}
parentNode.expand();parentNode=parentNode.parent;}
parentNodeBeforeRoot.expand();}}}}
if(currSearchFoundTags!=null&&currSearchFoundTags.length>0){for(i=0;i<currSearchFoundTags.length;i++){if(currSearchFoundTags[i].getLabelEl()!=null){currSearchFoundTags[i].getLabelEl().style.backgroundColor="DB7093";}}}
previousSearchFoundTags=currSearchFoundTags;}
else{alert('Please type in the search field');}},searchTagsAll:function(){var searchThisTag=document.getElementById('tags_search').value;if(searchThisTag!=null&&searchThisTag.length>0){var tagName=new Array(1);tagName[0]=searchThisTag;window.setTimeout('ajaxStatus.hideStatus()',500);var callback={success:function(r){SUGAR.util.evalScript(r.responseText);}}
postData='searchTagName='+YAHOO.lang.JSON.stringify(tagName)+'&module=KBTags&action=SelectCreateApplyAndMoveTags&to_pdf=1';YAHOO.util.Connect.asyncRequest('POST','index.php',callback,postData);}
else{alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_TYPE_TAG_NAME_TO_SEARCH'));}},treeInit:function(divId,tagId){document.getElementById('tags_tree').style.display='';tree=new YAHOO.widget.TreeView('tagstree');tree.setDynamicLoad(loadDataForNode,1);tags=document.getElementById(tagId);var tagVal=tags.value;var tags_comma=tagVal.split(",");tags_commaN="";for(var i=0;i<tags_comma.length;i++){if(tags_comma[i].length>0){currT=tags_comma[i];for(var t=0;t<currT.length;t++){if(currT.indexOf('/')==0){currT=currT.substring(1);}}
tags_commaN=tags_commaN+currT+",";}}
tags_commaN=tags_commaN.substring(0,tags_commaN.lastIndexOf(','));var tags_slash=tags_commaN.split("/");tags_slashN="";for(var k=0;k<tags_slash.length;k++){if(tags_slash[k].length>0){currT=tags_slash[k];for(var t=0;t<currT.length;t++){if(currT.indexOf('&')==0){currT=currT.substring(1);}}
tags_slashN=tags_slashN+currT+"/";}}
tags_comma=tags_slashN.substring(0,tags_slashN.lastIndexOf('/'));if(checkDups(tags_comma,",")!=null){alert(checkDups(tags_comma,","));return false;}
if(tags_comma!=null&&tags_comma.length>0){var root=tree.getRoot();var myobj={label:"Root",id:"Root"};var rootNode=new YAHOO.widget.TextNode(myobj,root,false);rootNode.expanded=true;tags_comma=tags_comma.split(",");var tmpNode=new Array();for(var i=0;i<tags_comma.length;i++){var tags_slash=tags_comma[i].split("/");for(var j=0;j<tags_slash.length;j++){var currTag=tags_slash[j];if(currTag!=null&&currTag.length>0){myobj={label:currTag,id:currTag};if(j==0){tmpNode[j]=new YAHOO.widget.TextNode(myobj,rootNode,false);tmpNode[j].expanded=true;tmpNode[j].iconMode=0;}
else{tmpNode[j]=new YAHOO.widget.TextNode(myobj,tmpNode[j-1],false);tmpNode[j].expanded=true;tmpNode[j].iconMode=0;}}}}
tree.subscribe("expand",function(node){});tree.subscribe("collapse",function(node){});tree.subscribe("labelClick",function(node){});}
tree.draw();},modalInit:function(){SUGAR.kb.hideMessageAndNode();document.getElementById('dialog1').style.display='';var handleCancel=function(){this.cancel();}
var handleSubmit=function(){tree=new YAHOO.widget.TreeView('tagstree');document.getElementById('Linked_Tags').style.display='';var linked_tags=document.getElementById('Linked_Tags');var attId=document.createElement('input');attId.setAttribute('id','t1');attId.setAttribute('name','t1');attId.setAttribute('tabindex','120');attId.setAttribute('type','text');attId.setAttribute('disabled',true);attId.setAttribute('value',tree.getNodeByIndex(1));linked_tags.appendChild(attId);this.submit();}
var myButtons=[];ajaxStatus.showStatus(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_LAUNCHING_TAG_BROWSING'));if(typeof myDialog==="undefined"){myDialog=new YAHOO.widget.SimpleDialog('dialog1',{visible:false,fixedcenter:true,centered:true,modal:true,draggable:false});myDialog.render(document.body);}
previousNodesCount=0;var selectCreateTags='Select Create Tags';fillInTags=function(data){try{eval(data.responseText);}
catch(e){result=new Array();result['body']='There was an error handling this request.';}
myDialog.setHeader('Tags');document.getElementById('jsonresults').innerHTML=result['body'];var listeners=new YAHOO.util.KeyListener(document,{keys:27},{fn:function(){this.hide();},scope:myDialog,correctScope:true});myDialog.cfg.queueProperty("keylisteners",listeners);myDialog.show();myDialog.center();SUGAR.util.evalScript(result['body']);window.setTimeout('ajaxStatus.hideStatus()',1000);}
var postData='tagsMode='+YAHOO.lang.JSON.stringify(selectCreateTags)+'&module=KBTags&action=SelectCreateApplyAndMoveTags&to_pdf=1';var callback={success:fillInTags,failure:fillInTags};YAHOO.util.Connect.asyncRequest('POST','index.php',callback,postData);},modalClose:function(treeid){var isThisSearchScreen=false;searchID=document.getElementById('modal_close_search');if(searchID!=null&&typeof(searchID)!='undefined'){isThisSearchScreen=true;}
var createNodeMessage=document.getElementById('CreateNodeMessage');var tagsCreate=document.getElementById('tagsCreate');tree=new YAHOO.widget.TreeView('treeid');var node=YAHOO.namespace(treeid).selectednode;var currT=document.getElementsByName('docTagIds[]');var savedTags=document.getElementsByName('savedTagIds[]');var tagId=node.data.id;var tagExists=false;var nodeMessageExists=false;if(currT!=null){for(i=0;i<currT.length;i++){if(node.data.id==currT[i].value){tagExists=true;break;}}}
if(isThisSearchScreen){if(node.data.id=='All_Tags'){clickedNode='';alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_ROOT_TAG_MESSAGE'));return;}
document.getElementById('tag_id').value=node.data.id;document.getElementById('tag_name').value=SUGAR.kb.getTagName(node,false);myDialog.submit();}else{if(savedTags!=null){for(i=0;i<savedTags.length;i++){if(node.data.id==savedTags[i].value){tagExists=true;break;}}}
if((createNodeMessage!=null&&createNodeMessage.style.display=='none')&&(tagsCreate!=null&&tagsCreate.style.display=='none')){if(node.data.id=='All_Tags'){clickedNode='';alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_ROOT_TAG_MESSAGE'));return;}
if(!tagExists){clickedNode='';link_tags=document.getElementById("Linked_Tags");link_tags.style.display='';var new_tag_row=document.createElement('div');new_tag_row.size='500px';var docTagName=document.createElement('input');docTagName.setAttribute('id','docTagNames[]');docTagName.setAttribute('name','docTagNames[]');docTagName.setAttribute('type','hidden');docTagName.setAttribute('disabled',true);docTagName.setAttribute('value',SUGAR.kb.getTagName(node,false));var new_row_button_remove_tag=document.createElement("img");new_row_button_remove_tag.setAttribute("src","index.php?entryPoint=getImage&themeName="+SUGAR.themes.theme_name+"&imageName=delete_inline.gif");new_row_button_remove_tag.setAttribute("align","absmiddle");new_row_button_remove_tag.setAttribute("border","0");var docTagId=document.createElement('input');docTagId.setAttribute('id','docTagIds[]');docTagId.setAttribute('name','docTagIds[]');docTagId.setAttribute('size','10');docTagId.setAttribute('type','hidden');docTagId.setAttribute('value',tagId);var removeTag=document.createElement('input');removeTag.type='button';removeTag.value='Remove';removeTag.onclick=function(){this.parentNode.parentNode.removeChild(this.parentNode);}
new_row_button_remove_tag.onclick=function(){this.parentNode.parentNode.removeChild(this.parentNode);}
new_tag_row.appendChild(docTagName);new_tag_row.appendChild(new_row_button_remove_tag);new_tag_row.appendChild(document.createTextNode(' '));new_tag_row.appendChild(document.createTextNode(SUGAR.kb.getTagName(node,false)));new_tag_row.appendChild(docTagId);link_tags.appendChild(new_tag_row);}
myDialog.submit();}
else{document.getElementById('CreateNodeMessage').style.display='none';var prevNodeId=document.getElementById('tag_selected_id').value;if(clickedNode.data==undefined){}
else{clickedNode.getLabelEl().style.backgroundColor="white";}
document.getElementById('tag_new').disabled=false;document.getElementById('Ok').disabled=false;document.getElementById('tag_new').style.visibility="visible";document.getElementById('Ok').style.visibility="visible";document.getElementById('tag_selected_id').value=tagId;document.getElementById('tagsCreate').style.display='';node.getLabelEl().style.backgroundColor="CCFFFF";clickedNode=node;}}},selectTagNode:function(treeid){if(document.getElementById('CreateNodeMessage').style.display=='none'){}
else{var createNodeMessage=document.getElementById('CreateNodeMessage');tree=new YAHOO.widget.TreeView('treeid');var node=YAHOO.namespace(treeid).selectednode;var currT=document.getElementsByName('docTagIds[]');var tagId=node.data.id;var tagExists=false;var nodeMessageExists=false;document.getElementById('CreateNodeMessage').style.display='';var prevNodeId=document.getElementById('tag_selected_id').value;if(clickedNode.data==undefined){}
else{clickedNode.getLabelEl().style.backgroundColor="white";}
document.getElementById('CreateNodeMessage').innerHTML=SUGAR.kb.getTagNameAdmin(node,true);document.getElementById('tag_new').disabled=false;document.getElementById('Ok').disabled=false;document.getElementById('tag_new').style.visibility="visible";document.getElementById('Ok').style.visibility="visible";document.getElementById('tag_selected_id').value=tagId;document.getElementById('CreateNode').style.display='';node.getLabelEl().style.backgroundColor="CCFFFF";clickedNodeMove=node;}},selectTagToMoveArticles:function(){var createNodeM=document.getElementById('CreateNodeMove');var node=YAHOO.namespace('tagstreeMoveDocsModal').selectednode;var tagId=node.data.id;var prevNodeId=document.getElementById('tag_selected_id').value;if(clickedNodeMove.data==undefined){}
else{clickedNodeMove.getLabelEl().style.backgroundColor="white";}
document.getElementById('CreateNodeMove').innerHTML=SUGAR.kb.getTagName(node,true);document.getElementById('Move').style.visibility="visible";document.getElementById('Cancel_Move').style.visibility="visible";document.getElementById('tag_selected_id').value=tagId;tagsTreeModalMoveDocs.setHeader(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_MOVING_ARTICLES_TO_TAG'));node.getLabelEl().style.backgroundColor="CCFFFF";clickedNodeMove=node;},selectTagToApplyArticles:function(){var selectedApplyTags=document.getElementsByName('selected_apply_tags[]');var checked=false;for(i=0;i<selectedApplyTags.length;i++){if(selectedApplyTags[i].checked){checked=true;}}
if(checked){document.getElementById('CreateNodeApply').innerHTML=SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_CLICK_APPLY_TAG');document.getElementById('Apply').style.visibility="visible";document.getElementById('Cancel_Apply').style.visibility="visible";}
else{document.getElementById('CreateNodeApply').innerHTML='<b><font COLOR=red>'+SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_TAGS_FROM_TREE')+'</b>';document.getElementById('Apply').style.visibility="hidden";document.getElementById('Cancel_Apply').style.visibility="hidden";}},selectTagToApplyArticles:function(){var selectedApplyTags=document.getElementsByName('selected_apply_tags[]');var checked=false;for(i=0;i<selectedApplyTags.length;i++){if(selectedApplyTags[i].checked){checked=true;}}
if(checked){document.getElementById('CreateNodeApply').innerHTML=SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_CLICK_APPLY_TAG');document.getElementById('Apply').style.visibility="visible";document.getElementById('Cancel_Apply').style.visibility="visible";}
else{document.getElementById('CreateNodeApply').innerHTML='<b><font COLOR=red>'+SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_TAGS_FROM_TREE')+'</b>';document.getElementById('Apply').style.visibility="hidden";document.getElementById('Cancel_Apply').style.visibility="hidden";}},getTagNameAdmin:function(node,newNode){if(node.depth>0){tagName='';currNode='';for(i=0;i<=node.depth;i++){if(i==0){tagName=node.data.label.substring(node.data.label.lastIndexOf('>')+1);tagName=tagName.substring(0,tagName.indexOf('('));}
if(i==1){currNode=node.parent;tagDelimName=currNode.data.label.substring(currNode.data.label.lastIndexOf('>')+1);tagName=tagDelimName.substring(0,tagDelimName.indexOf('('))+'/'+tagName;}
if(i>1){currNode=currNode.parent;tagDelimName=currNode.data.label.substring(currNode.data.label.lastIndexOf('>')+1);tagName=tagDelimName.substring(0,tagDelimName.indexOf('('))+'/'+tagName;}}}else{if(node.data.label.lastIndexOf('>')!=-1&&tagName.indexOf('(')!=-1){tagName=node.data.label.substring(node.data.label.lastIndexOf('>')+1);tagName=tagName.substring(0,tagName.indexOf('('));}
else{tagName=node.data.label;}}
if(newNode){if(tagName.length>50){tagName='...'+tagName.substring(tagName.length-48)+'/';}
else{tagName=tagName+'/';}}
if(tagName.indexOf('/')==0){tagName=tagName.substring(1);}
return tagName;},getTagName:function(node,newNode){if(node.depth>0){tagName='';currNode='';for(i=0;i<=node.depth;i++){if(i==0){tagName=node.data.label.substring(0,node.data.label.indexOf('('));}
if(i==1){currNode=node.parent;tagName=currNode.data.label.substring(0,currNode.data.label.indexOf('('))+'/'+tagName;}
if(i>1){currNode=currNode.parent;tagName=currNode.data.label.substring(0,currNode.data.label.indexOf('('))+'/'+tagName;}}}else{if(node.data.label.indexOf('(')!=-1){tagName=node.data.label.substring(0,node.data.label.indexOf('('));}
else{tagName=node.data.label;}}
if(tagName.indexOf('/')==0){tagName=tagName.substring(1);}
if(newNode){if(tagName.length>50){tagName='...'+tagName.substring(tagName.length-50)+'/';}
else{tagName=tagName+'/';}}
return tagName;},addTags:function(){link_tags=document.getElementById("Linked_Tags");link_tags.style.display='';var addTagEl=document.getElementById('addTag');if(addTagEl!=null){var newVal=addTagEl.value+' '+tags.value;addTagEl.setAttribute('value',newVal);}
else{var attId=document.createElement('input');attId.setAttribute('id','addTag');attId.setAttribute('name','addTag');attId.setAttribute('tabindex','220');attId.setAttribute('type','text');attId.setAttribute('disabled',true);attId.setAttribute('value',tags.value);link_tags.appendChild(attId);}},loadDataForNode:function(node,onCompleteCallback){var id=node.data.id;if(id!='Root Tag'){}
onCompleteCallback();},checkDups:function(tagsVal,separator){var tags=tagsVal.split(separator);var dups=null;for(var i=0;i<tags.length;i++){if(tags[i].length>0){for(var j=0;j<tags.length;j++){var tagI="";var tagJ="";if(tags[i].indexOf('/')!=-1){tagI=tags[i].substring(0,tags[i].indexOf('/'));}
else{tagI=tags[i];}
if(tags[j].indexOf('/')!=-1){tagJ=tags[j].substring(0,tags[j].indexOf('/'));}
else{tagJ=tags[j];}
if(tagI!=null&&tagJ!=null){if(i!=j&&tagI.toLowerCase()==tagJ.toLowerCase()){dups="Duplicate tags "+tagI+" and "+tagJ+" at the same level";}}}}}},multiAttachments:function(list_target,elmentsName,site_url,theme_name,isAtt){this.list_target=list_target;this.count=0;this.id=0;this.addElement=function(element){if(element.tagName=='INPUT'&&element.type=='file'){var currCount=this.id++;element.name=elmentsName+currCount;element.id=elmentsName+currCount;element.multi_selector=this;element.onchange=function(){var callback={upload:function(r){var rets=YAHOO.lang.JSON.parse(r.responseText);var thediv=document.getElementById(rets['div_name']);if(rets['status']=='failed'){thediv.parentNode.removeChild(thediv);alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_NOT_A_VALID_FILE'));}
else{if(!isAtt&&rets['is_file_image']==0){thediv.parentNode.removeChild(thediv);alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_NOT_A_VALID_FILE'));}
else{thediv.setAttribute('id',rets['new_file_name']);}}}}
var divAndEl=new Array(2);var div_name='div_number'+currCount;divAndEl[0]=div_name;divAndEl[1]=element.name;var url='index.php?module=KBDocuments&action=KbdocAttachments&to_pdf=1&div_name_and_El='+divAndEl;YAHOO.util.Connect.setForm(document.getElementById("upload_form"),true,true);YAHOO.util.Connect.asyncRequest('POST',url,callback,null);var theForm=document.getElementById('EditView');var new_element=document.createElement('input');new_element.type='file';this.parentNode.insertBefore(new_element,this);this.multi_selector.addElement(new_element);this.multi_selector.addListRow(this,div_name);this.style.display='none';};this.count++;this.current_element=element;}else{alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_ERROR_NOT_A_FILE_INPUT_ELEMENT'));};};this.addListRow=function(element,div_id){var new_row=document.createElement('div');new_row.setAttribute('id',div_id);var new_row_button_remove=document.createElement('img');new_row_button_remove.setAttribute("alt","Remove");new_row_button_remove.setAttribute("src","index.php?entryPoint=getImage&themeName="+SUGAR.themes.theme_name+"&imageName=delete_inline.gif");var new_row_file_name=document.createElement('pre');var new_row_chk_box=document.createElement('input');new_row_chk_box.setAttribute('id','checkBoxFile[]');new_row_chk_box.setAttribute('name','checkBoxFile[]');new_row_chk_box.type='checkbox';new_row_chk_box.checked=false;new_row_chk_box.disabled=true;var new_row_attach_file=document.createElement('input');new_row_attach_file.type='image';new_row_attach_file.value='/index.php?entryPoint=getImage&themeName='+SUGAR.themes.theme_name+'&imageName=company_logo.png';new_row_attach_file.disabled='true';var imgElement=document.createElement("img");imgElement.setAttribute("src","index.php?entryPoint=getImage&themeName="+SUGAR.themes.theme_name+"&imageName=Accounts.gif");imgElement.setAttribute("align","absmiddle");imgElement.setAttribute("alt","File");imgElement.setAttribute("border","0");imgElement.setAttribute("height","18");imgElement.setAttribute("width","16");var new_row_button_embed=document.createElement("img");new_row_button_embed.setAttribute("src","index.php?entryPoint=getImage&themeName="+SUGAR.themes.theme_name+"&imageName=plus_inline.gif");new_row_button_embed.setAttribute("align","absmiddle");new_row_button_embed.setAttribute("alt","Embed");new_row_button_embed.setAttribute("border","0");new_row.element=element;element.size='50';new_row_button_remove.onclick=function(){if(isAtt){var filename=element.value.replace(/\\/g,'/')
var text=filename.split("/");nbr_elements=text.length;var currVal=document.getElementById('removed_files').value;if(currVal!=''){currVal=currVal+','+text[nbr_elements-1];}
else{currVal=text[nbr_elements-1];}
document.getElementById('removed_files').value=currVal;}
filename=this.parentNode.parentNode.id;if(!isAtt){var tiny=tinyMCE.getInstanceById('body_html');var currValTiny=tiny.getContent();while(currValTiny.indexOf(unescape(filename))!=-1){currValTiny=currValTiny.replace(unescape(filename),'QW%%^%%WQ');currValTiny=currValTiny.replace(/<img[^<]*QW%%\^%%WQ[^>]*>?/,'');}
tiny.setContent(currValTiny);}
if(isAtt){currDiv=document.getElementById(this.parentNode.id);currDiv.parentNode.removeChild(currDiv);}
else{currDiv=document.getElementById(this.parentNode.parentNode.id);currDiv.parentNode.removeChild(currDiv);}
return false;};new_row_button_embed.onclick=function(){var filename=this.parentNode.parentNode.id;embedImage="<img src=\"index.php?entryPoint=download&type=SugarFieldImage&isTempFile=1&id="+unescape(filename)+"\">";var tiny=tinyMCE.getInstanceById('body_html');tiny.getWin().focus();tiny.execCommand('mceInsertRawHTML',false,embedImage);};new_row_file_name_tab=element.value.split("\\");nbr_elements=new_row_file_name_tab.length;new_row_file_name.innerHTML=new_row_file_name_tab[nbr_elements-1];if(isAtt){new_row.appendChild(new_row_button_remove);var spn=document.createElement("span");spn.appendChild(document.createTextNode(' '));var new_row_file_name=document.createElement('pre');spn.appendChild(new_row_file_name.appendChild(document.createTextNode(new_row_file_name_tab[nbr_elements-1])));new_row.appendChild(spn);}
else{var spn=document.createElement("span");spn.appendChild(new_row_button_remove);spn.appendChild(document.createTextNode(' '));spn.appendChild(new_row_button_embed);spn.appendChild(document.createTextNode(' '));var new_row_file_name=document.createElement('pre');spn.appendChild(new_row_file_name.appendChild(document.createTextNode(new_row_file_name_tab[nbr_elements-1])));new_row.appendChild(spn);}
list_target.appendChild(new_row);};},copyTinyVal:function(){var tiny=tinyMCE.getInstanceById('body_html');if((null!=tiny)||("undefined"!=typeof(tiny))){var currValTiny=tiny.getContent();document.getElementById('tiny_vals').value=currValTiny;}else{document.getElementById('tiny_vals').value=document.getElementById('body_html').value;}},addUploadFileAttachments:function(form_name){var chForm=document.getElementById('upload_div');var theForm=document.getElementById(form_name);var elems=chForm.getElementsByTagName("input");var count=0;for(var i=0;i<elems.length;i++){if(elems[i].type=="file"){count++;}}
for(var i=0;i<count-1;i++){var el=document.getElementsByName('kbdoc_attachment'+i);if(el[0]!=null){theForm.appendChild(el[0]);}}
var chForm=document.getElementById("upload_form");var elems=chForm.getElementsByTagName("input");for(var i=0;i<elems.length;i++){var el=elems[i];if(el.id=='checkBoxFile[]'){theForm.appendChild(el);}}},addDocTags:function(form_name){var theForm=document.getElementById(form_name);var tagDiv=document.getElementById("Linked_Tags");var elems=theForm.getElementsByTagName("input");var elems1=tagDiv.getElementsByTagName("input");for(var i=0;i<elems1.length;i++){var el=elems1[i];if(el.id=='docTagIds[]'){theForm.appendChild(el);}}
for(var i=0;i<elems.length;i++){var el=elems[i];if(el.id=='docTagIds[]'){theForm.appendChild(el);}
if(el.id.indexOf('docTagIds')>=0||el.id=='docTagIds[]'){theForm.appendChild(el);}}},externalChecked:function(defalut_team_name,default_team_id){if(document.getElementById('is_external').checked){var temp_array=[];temp_array['name']='Global';temp_array['id']='1';collection['EditView_team_name'].replace_first(temp_array);}
else{var temp_array=[];temp_array['name']=defalut_team_name;temp_array['id']=default_team_id;collection['EditView_team_name'].replace_first(temp_array);}},externalCheckedOnLoad:function(){if(document.getElementById('is_external').checked){var temp_array=[];temp_array['name']='Global';temp_array['id']='1';collection['EditView_team_name'].replace_first(temp_array);}},statusChecked:function(){if(document.getElementById('status_id')!=null&&document.getElementById('status_id').value=='In Review'&&document.getElementById('kbdoc_approver_name').value==''){document.getElementById('kbdoc_approver_name').value='admin';document.getElementById('kbdoc_approver_id').value='1';}},strikeOutFromImage:function(currTagId,currBox,tagOrDoc){var currTag=document.getElementById(currTagId);var boxState=document.getElementById(currBox).checked;if(!boxState){boxState=true;}
else{boxState=false;}
if(boxState){currTag.innerHTML="<strike><strong><font COLOR=red>"+currTag.innerHTML+"</font></>";}
else{currTag.innerHTML=currTag.innerHTML.replace("<STRIKE>",'&#32');currTag.innerHTML=currTag.innerHTML.replace("</STRIKE>",'&#32');currTag.innerHTML=currTag.innerHTML.replace("<strike>",'&#32');currTag.innerHTML=currTag.innerHTML.replace("</strike>",'&#32');currTag.innerHTML=currTag.innerHTML.replace("red",'');}
document.getElementById(currBox).checked=boxState;if(tagOrDoc==0){var currVal=document.getElementById('removed_tags').value;if(currVal!=''){var tags=currVal.split(",");var exists=false;tags_elements=tags.length;for(i=0;i<tags_elements;i++){if(tags[i]==currBox){exists=true;break;}}
if(exists){if(tags_elements>1){currBox=currBox+',';currVal=currVal.replace(currBox,'');}
else{currVal=currVal.replace(currBox,'');}}
else{currVal=currVal+','+currBox;}}
else{currVal=currBox;}
document.getElementById('removed_tags').value=currVal;}
if(tagOrDoc==1){var currVal=document.getElementById('removed_attachments').value;if(currVal!=''){var tags=currVal.split(",");var exists=false;tags_elements=tags.length;for(i=0;i<tags_elements;i++){if(tags[i]==currBox){exists=true;break;}}
if(exists){if(tags_elements>1){currBox=currBox+','
currVal=currVal.replace(currBox,'');}
else{currVal=currVal.replace(currBox,'');}}
else{currVal=currVal+','+currBox;}}
else{currVal=currBox;}
document.getElementById('removed_attachments').value=currVal;}},strikeOutFromBox:function(currTagId,currBox){var currTag=document.getElementById(currTagId);var boxState=document.getElementById(currBox).checked;if(boxState){currTag.innerHTML="<strike><strong><font COLOR=red>"+currTag.innerHTML+"</font></>";}
else{currTag.innerHTML=currTag.innerHTML.replace("<STRIKE>",'&#32');currTag.innerHTML=currTag.innerHTML.replace("</STRIKE>",'&#32');currTag.innerHTML=currTag.innerHTML.replace("<strike>",'&#32');currTag.innerHTML=currTag.innerHTML.replace("</strike>",'&#32');currTag.innerHTML=currTag.innerHTML.replace("red",'');}
document.getElementById(currBox).checked=boxState;},setCheckBox:function(currBox){var chkBox=document.getElementsByName('remove_atts[]');var found=false;for(i=0;i<chkBox.length;i++){if(chkBox[i].value==currBox){if(chkBox[i].checked){chkBox[i].checked=false;chkBox[i].value='';}
else{chkBox[i].checked=true;}
found=true;break;}}
if(!found){chkBox[chkBox.length-1].checked=true;chkBox[chkBox.length-1].value=currBox;}},hideShowMoreTags:function(span){if(span=='more_options_img'){document.getElementById('more_tags_div').style.display='';document.getElementById('more_tags_img').style.display='none';document.getElementById('less_tags_img').style.display='';}else{document.getElementById('more_tags_div').style.display='none';document.getElementById('more_tags_img').style.display='';document.getElementById('less_tags_img').style.display='none';}},cancelAdminActions:function(){document.getElementById('action_id').value='';document.getElementById('adminTag').style.display='';document.getElementById('createTag').style.display='none';document.getElementById('deleteTag').style.display='none';document.getElementById('renameTag').style.display='none';document.getElementById('moveArticles').style.display='none';document.getElementById('applyTags').style.display='none';document.getElementById('deleteArticles').style.display='none';document.getElementById('tag_message').innerHTML='<b><font COLOR=red>'+SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_PARENT_TAG_MESSAGE')+'</b>';document.getElementById('tag_message_rename').innerHTML='<b><font COLOR=red>'+SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SELECT_TAG_TO_BE_RENAMED_FROM_TREE')+'</b>';document.getElementById('tag_new').style.visibility="hidden";document.getElementById('tag_save').style.visibility="hidden";},adminActions:function(){var currAction=document.getElementById('action_id');if(currAction.value==''){SUGAR.kb.actionsDropdown('adminTag');}
if(currAction.value=='Create New Tag'){SUGAR.kb.actionsDropdown('createTag');}
if(currAction.value=='Rename Tag'){SUGAR.kb.actionsDropdown('renameTag');}
if(currAction.value=='Delete Tag'){SUGAR.kb.actionsDropdown('deleteTag');}
if(currAction.value=='Move Selected Articles'){SUGAR.kb.actionsDropdown('moveArticles');}
if(currAction.value=='Apply Tags On Articles'){SUGAR.kb.actionsDropdown('applyTags');}
if(currAction.value=='Delete Selected Articles'){SUGAR.kb.actionsDropdown('deleteArticles');}},actionsDropdown:function(actionDiv){document.getElementById('adminTag').style.display='none';document.getElementById('createTag').style.display='none';document.getElementById('deleteTag').style.display='none';document.getElementById('renameTag').style.display='none';document.getElementById('moveArticles').style.display='none';document.getElementById('applyTags').style.display='none';document.getElementById('deleteArticles').style.display='none';document.getElementById(actionDiv).style.display='';},adminClick:function(){node=YAHOO.namespace("tagstree").selectednode;var currAction=document.getElementById('action_id');if(currAction.value==''||currAction.value=='Delete Tag'){return;}
if(currAction.value=='Create New Tag'){document.getElementById('tag_message').innerHTML=SUGAR.kb.getTagNameAdmin(node,true);document.getElementById('tag_selected_id').value=node.data.id;document.getElementById('tag_new').style.visibility="visible";document.getElementById('tag_save').style.visibility="visible";}
if(currAction.value=='Rename Tag'){if(node.parent=="RootNode"||node.data.id=='All_Tags'){alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_ROOT_TAG_CAN_NOT_BE_RENAMED'));}
else{var rename_tag=SUGAR.kb.getTagNameAdmin(node,true);rename_tag=rename_tag.substring(0,rename_tag.lastIndexOf('/'));document.getElementById('tag_message_rename').innerHTML=rename_tag;document.getElementById('tag_selected_rename_id').value=node.data.id;document.getElementById('tag_selected_rename_parent_id').value=node.parent.data.id;document.getElementById('tag_name_rename').style.visibility="visible";document.getElementById('tag_save_rename').style.visibility="visible";}}},renameTag:function(admin){var tagsTree=YAHOO.widget.TreeView.trees['tagstree'];var root=tagsTree.getRoot();var tag_id='';var parent_tag_id='';if(!(document.getElementById('tag_selected_rename_id').value=='')&&(document.getElementById('tag_selected_rename_id').value.length>0)){tag_id=document.getElementById('tag_selected_rename_id').value;}
if(!(document.getElementById('tag_selected_rename_parent_id').value=='')&&(document.getElementById('tag_selected_rename_parent_id').value.length>0)){parent_tag_id=document.getElementById('tag_selected_rename_parent_id').value;}
var newTag=document.getElementById('tag_name_rename').value;if(newTag!=null&&newTag.length>0){var nodeChildExists=false;if(parent_tag_id!=null&&parent_tag_id=='RootNode'){var root=tagsTree.getRoot();if(root.children.length>0){for(i=0;i<root.children.length;i++){var currChild=root.children[i].label;if(admin)currChild=currChild.substring(currChild.lastIndexOf('>')+1);currChild=currChild.substring(0,currChild.indexOf('('));if(newTag.toLowerCase()==currChild.toLowerCase()){nodeChildExists=true;}}}}
if(!nodeChildExists){ajaxStatus.showStatus(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_SAVING_THE_TAG'));if(admin==null||admin=='undefined'){admin=false;}
var idName=new Array(3);idName[0]=newTag;idName[1]=tag_id;idName[2]=parent_tag_id;var treeDiv=document.getElementById('tagstree');window.setTimeout('ajaxStatus.hideStatus()',500);var callback={success:function(r){if(r.responseText==1){alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_TAG_ALREADY_EXISTS'));}
else{SUGAR.util.evalScript(r.responseText);var currTagName='';var storedTag=document.getElementById('tag_message_rename').innerHTML;if(storedTag.indexOf('/')!=-1){currTagName=storedTag.substring(storedTag.lastIndexOf('/')+1);}
else{currTagName=storedTag;}
storedTag=storedTag.replace(currTagName,newTag);document.getElementById('tag_message_rename').innerHTML=storedTag;}}}
postData='newTagName='+YAHOO.lang.JSON.stringify(idName)+'&module=KBTags&action=RenameTagsAdmin&to_pdf=1';YAHOO.util.Connect.asyncRequest('POST','index.php',callback,postData);if(admin){document.getElementById('tag_name_rename').value='';}
else{document.getElementById('tags_search').value=newTag;searchTree(false);document.getElementById('tags_search').value='';SUGAR.kb.hideMessageAndNode();}
previousNodesCount=YAHOO.widget.TreeView.trees['tagstree']._nodes.length;previousSearchFoundTags=new Array();clickedNode='';}
else{alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_TAG_ALREADY_EXISTS'));}}
else{alert(SUGAR.kb.getLocalizedLabels('KBDocuments','LBL_TYPE_THE_NEW_TAG_NAME'));}},paginateList:function(url,mode){if(mode=='browse'){var callback={success:function(o){var targetdiv=document.getElementById('selected_directory_children');targetdiv.innerHTML=o.responseText;SUGAR.util.evalScript(o.responseText);},failure:function(o){}}
var trobj=YAHOO.util.Connect.asyncRequest('POST',url,callback);}else{document.location.href=url;}}}}();
