<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Master Subscription
 * Agreement ("License") which can be viewed at
 * http://www.sugarcrm.com/crm/master-subscription-agreement
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *  (i) the "Powered by SugarCRM" logo and
 *  (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2012 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/

 


function create_default_reports($is_upgrade=false) {
    global $current_language;

    $lang_strings = return_module_language($current_language, 'Reports');

    $default_reports = array();

    
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_1'], '{"display_columns":[{"name":"name","label":"Opportunity Name","table_key":"self"},{"name":"name","label":"Name","table_key":"Opportunities:accounts"},{"name":"amount_usdollar","label":"Amount","table_key":"self"},{"name":"date_closed","label":"Expected Close Date","table_key":"self"},{"name":"probability","label":"Probability (%)","table_key":"self"},{"name":"user_name","label":"User Name","table_key":"Opportunities:assigned_user_link"}],"module":"Opportunities","group_defs":[],"summary_columns":[],"report_name":"Current Quarter Forecast","do_round":1,"numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"tabular","full_table_list":{"self":{"value":"Opportunities","module":"Opportunities","label":"Opportunities"},"Opportunities:accounts":{"name":"Opportunities  >  Accounts","parent":"self","link_def":{"name":"accounts","relationship_name":"accounts_opportunities","bean_is_lhs":false,"link_type":"one","label":"Accounts","table_key":"Opportunities:accounts"},"dependents":["display_cols_row_2"],"module":"Accounts","label":"Accounts"},"Opportunities:assigned_user_link":{"name":"Opportunities  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"opportunities_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Opportunities:assigned_user_link"},"dependents":["display_cols_row_6"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"date_closed","table_key":"self","qualifier_name":"between_dates","runtime":1,"input_name0":"2009-10-01","input_name1":"2009-12-31"}}},"chart_type":"none"}','tabular');
    //$default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_1'], '{"display_columns":[{"name":"name","label":"Opportunity Name","table_key":"self"},{"name":"name","label":"Account Name","table_key":"accounts"},{"name":"amount_usdollar","label":"Amount","table_key":"self"},{"name":"date_closed","label":"Expected Close Date","table_key":"self"},{"name":"probability","label":"Probability (%)","table_key":"self"},{"name":"full_name","label":"Assigned to","table_key":"assigned_user_link"}],"summary_columns":[],"order_by":[{"name":"probability","label":"Probability (%)","table_key":"self","sort_dir":"a"}],"filters_def":[{"name":"date_closed","table_key":"self","qualifier_name":"between_dates","input_name0":"2005-07-01","input_name1":"2005-09-30"}],"group_defs":[],"links_def":["accounts","team_link","created_by_link","modified_user_link","assigned_user_link"],"module":"Opportunities","report_name":"Current Quarter Forecast\\n","report_type":"tabular"}','tabular');

    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_2'], '{"display_columns":[{"name":"name","label":"Opportunity Name","table_key":"self"},{"name":"name","label":"Account Name","table_key":"accounts"},{"name":"amount_usdollar","label":"Amount","table_key":"self"},{"name":"description","label":"Description","table_key":"self"},{"name":"next_step","label":"Next Step","table_key":"self"},{"name":"date_closed","label":"Expected Close Date","table_key":"self"},{"name":"probability","label":"Probability (%)","table_key":"self"}],"summary_columns":[],"order_by":[{"name":"probability","label":"Probability (%)","table_key":"self","sort_dir":"a"}],"filters_def":[],"group_defs":[],"links_def":["accounts","team_link","created_by_link","modified_user_link","assigned_user_link"],"module":"Opportunities","report_name":"Detailed Forecast","report_type":"tabular"}','tabular');
    $default_reports[] = array('Accounts', $lang_strings['DEFAULT_REPORT_TITLE_3'], '{"display_columns":[{"name":"name","label":"Account Name","table_key":"self"},{"name":"phone_office","label":"Phone Office","table_key":"self"},{"name":"description","label":"Description","table_key":"self"},{"name":"annual_revenue","label":"Annual Revenue","table_key":"self"},{"name":"account_type","label":"Type","table_key":"self"},{"name":"full_name","label":"Assigned to","table_key":"assigned_user_link"}],"summary_columns":[],"filters_def":[{"name":"account_type","table_key":"self","qualifier_name":"is","input_name0":"Partner"}],"group_defs":[],"links_def":["member_of","team_link","created_by_link","modified_user_link","assigned_user_link"],"module":"Accounts","report_name":"Partner Account List","order_by":[],"report_type":"tabular"}','tabular');
    $default_reports[] = array('Accounts', $lang_strings['DEFAULT_REPORT_TITLE_4'], '{"display_columns":[{"name":"name","label":"Account Name","table_key":"self"},{"name":"website","label":"Website","table_key":"self"},{"name":"phone_office","label":"Phone Office","table_key":"self"},{"name":"description","label":"Description","table_key":"self"},{"name":"account_type","label":"Type","table_key":"self"},{"name":"full_name","label":"Assigned to","table_key":"assigned_user_link"}],"summary_columns":[],"filters_def":[{"name":"account_type","table_key":"self","qualifier_name":"is","input_name0":"Customer"}],"group_defs":[],"links_def":["member_of","team_link","created_by_link","modified_user_link","assigned_user_link"],"module":"Accounts","report_name":"Customer Account List","order_by":[],"report_type":"tabular"}','tabular');
    $default_reports[] = array('Contacts', $lang_strings['DEFAULT_REPORT_TITLE_5'], '{"display_columns":[{"name":"date_modified","label":"Last Modified","table_key":"self"},{"name":"full_name","label":"Contact Name","table_key":"self"},{"name":"phone_work","label":"Office Phone","table_key":"self"},{"name":"name","label":"Account Name","table_key":"accounts"},{"name":"alt_address_country","label":"Alternate Address Country","table_key":"self"},{"name":"full_name","label":"Assigned to","table_key":"assigned_user_link"}],"summary_columns":[],"filters_def":[{"name":"do_not_call","table_key":"self","qualifier_name":"equals","input_name0":["no"]}],"group_defs":[],"links_def":["accounts","reports_to_link","team_link","created_by_link","modified_user_link","assigned_user_link"],"order_by":[],"module":"Contacts","report_name":"Call list by last date modified","report_type":"tabular"}','tabular');
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_6'], '{"report_type":"summary","display_columns":[{"name":"lead_source","label":"Lead Source","table_key":"self"},{"name":"name","label":"Opportunity Name","table_key":"self"},{"name":"name","label":"Account Name","table_key":"accounts"},{"name":"amount_usdollar","label":"Amount","table_key":"self"},{"name":"sales_stage","label":"Sales Stage","table_key":"self"},{"name":"probability","label":"Probability (%)","table_key":"self"},{"name":"full_name","label":"Assigned to","table_key":"assigned_user_link"}],"summary_columns":[{"name":"lead_source","label":"Opportunities: Lead Source","table_key":"self"},{"name":"count","label":"Count","group_function":"count","table_key":"self"}],"order_by":[{"name":"amount_usdollar","label":"Amount","table_key":"self","sort_dir":"d"}],"filters_def":[],"group_defs":[{"name":"lead_source","label":"Lead Source","table_key":"self"}],"links_def":["accounts","team_link","created_by_link","modified_user_link","assigned_user_link"],"module":"Opportunities","report_name":"Opportunities by Lead Source","chart_type":"hBarF","chart_description":"","numerical_chart_column":"count"}','detailed_summary','hBarF');
    
    // Cases
    $default_reports[] = array('Cases', $lang_strings['DEFAULT_REPORT_TITLE_7'], '{"report_type":"summary","display_columns":[{"name":"case_number","label":"Cases: Number","table_key":"self"},{"name":"name","label":"Cases: Subject","table_key":"self"},{"name":"date_entered","label":"Cases: Date Created","table_key":"self"}],"summary_columns":[{"name":"count","label":"Count","group_function":"count","table_key":"self"},{"name":"status","label":"Cases: Status","table_key":"self","is_group_by":"visible"},{"name":"user_name","label":"Assigned to User: User Name","table_key":"self_link_0","is_group_by":"visible"}],"filters_def":[{"name":"status","table_key":"self","qualifier_name":"one_of","input_name0":["New","Assigned","Pending Input"]}],"filters_combiner":"AND","group_defs":[{"name":"user_name","label":"User Name","table_key":"self_link_0"},{"name":"status","label":"Status","table_key":"self"}],"full_table_list":{"self":{"parent":"","value":"Cases","module":"Cases","label":"Cases","children":{"self_link_0":"self_link_0"}},"self_link_0":{"parent":"self","children":[],"value":"assigned_user_link","label":"Assigned to User","link_def":{"name":"assigned_user_link","relationship_name":"cases_assigned_user","bean_is_lhs":"","link_type":"one","label":"Assigned to User","table_key":"self_link_0"},"module":"Users"}},"module":"Cases","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_7'] . '","chart_type":"hBarF","chart_description":"","numerical_chart_column":"count","assigned_user_id":"1"}', 'detailed_summary','hBarF');
    $default_reports[] = array('Cases', $lang_strings['DEFAULT_REPORT_TITLE_8'], '{"report_type":"summary","display_columns":[{"name":"case_number","label":"Cases: Number","table_key":"self"},{"name":"name","label":"Cases: Subject","table_key":"self"},{"name":"name","label":"Account: Name","table_key":"self_link_1"}],"summary_columns":[{"name":"date_entered","label":"Date Created","table_key":"self","qualifier":"month","is_group_by":"hidden","column_function":"month"},{"name":"count","label":"Count","group_function":"count","table_key":"self"},{"name":"date_entered","label":"Cases: Month: Date Created","column_function":"month","table_key":"self"},{"name":"user_name","label":"Assigned to User: User Name","table_key":"self_link_0","is_group_by":"visible"}],"filters_def":[{"name":"status","table_key":"self","qualifier_name":"one_of","input_name0":["New","Assigned","Pending Input"]}],"filters_combiner":"AND","group_defs":[{"name":"date_entered","label":"Date Created","table_key":"self","qualifier":"month","is_group_by":"hidden","column_function":"month"},{"name":"user_name","label":"User Name","table_key":"self_link_0"}],"full_table_list":{"self":{"parent":"","value":"Cases","module":"Cases","label":"Cases","children":{"self_link_0":"self_link_0","self_link_1":"self_link_1"}},"self_link_0":{"parent":"self","children":[],"value":"assigned_user_link","label":"Assigned to User","link_def":{"name":"assigned_user_link","relationship_name":"cases_assigned_user","bean_is_lhs":"","link_type":"one","label":"Assigned to User","table_key":"self_link_0"},"module":"Users"},"self_link_1":{"parent":"self","children":[],"value":"account","label":"Account","link_def":{"name":"account","relationship_name":"account_cases","bean_is_lhs":"","link_type":"one","label":"Account","table_key":"self_link_1"},"module":"Accounts"}},"module":"Cases","report_name":"Open Cases By Month By User","chart_type":"vBarF","chart_description":"","numerical_chart_column":"count","assigned_user_id":"1"}', 'detailed_summary','vBarF');
    $default_reports[] = array('Cases', $lang_strings['DEFAULT_REPORT_TITLE_9'], '{"report_type":"summary","display_columns":[{"name":"case_number","label":"Cases: Number","table_key":"self"},{"name":"name","label":"Cases: Subject","table_key":"self"},{"name":"name","label":"Account: Name","table_key":"self_link_1"}],"summary_columns":[{"name":"count","label":"Count","group_function":"count","table_key":"self"},{"name":"priority","label":"Cases: Priority","table_key":"self","is_group_by":"visible"},{"name":"user_name","label":"Assigned to User: User Name","table_key":"self_link_0","is_group_by":"visible"}],"filters_def":[{"name":"status","table_key":"self","qualifier_name":"one_of","input_name0":["New","Assigned","Pending Input"]}],"filters_combiner":"AND","group_defs":[{"name":"user_name","label":"User Name","table_key":"self_link_0"},{"name":"priority","label":"Priority","table_key":"self"}],"full_table_list":{"self":{"parent":"","value":"Cases","module":"Cases","label":"Cases","children":{"self_link_0":"self_link_0","self_link_1":"self_link_1"}},"self_link_0":{"parent":"self","children":[],"value":"assigned_user_link","label":"Assigned to User","link_def":{"name":"assigned_user_link","relationship_name":"cases_assigned_user","bean_is_lhs":"","link_type":"one","label":"Assigned to User","table_key":"self_link_0"},"module":"Users"},"self_link_1":{"parent":"self","children":[],"value":"account","label":"Account","link_def":{"name":"account","relationship_name":"account_cases","bean_is_lhs":"","link_type":"one","label":"Account","table_key":"self_link_1"},"module":"Accounts"}},"module":"Cases","report_name":"Open Cases By Priority By User","chart_type":"hBarF","chart_description":"","numerical_chart_column":"count","assigned_user_id":"1"}', 'detailed_summary','hBarF');
    $default_reports[] = array('Cases', $lang_strings['DEFAULT_REPORT_TITLE_10'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"date_entered","label":"Date Created","table_key":"self","qualifier":"month","is_group_by":"hidden","column_function":"month"},{"name":"count","label":"Count","group_function":"count","table_key":"self"},{"name":"date_entered","label":"Cases: Month: Date Created","column_function":"month","table_key":"self"}],"filters_def":[],"filters_combiner":"AND","group_defs":[{"name":"date_entered","label":"Date Created","table_key":"self","qualifier":"month","is_group_by":"hidden","column_function":"month"}],"full_table_list":{"self":{"parent":"","value":"Cases","module":"Cases","label":"Cases","children":[]}},"module":"Cases","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_10'] . '","chart_type":"vBarF","chart_description":"","numerical_chart_column":"count","assigned_user_id":"1"}', 'summary','vBarF');
    // Pipeline
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_11'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"amount_usdollar","label":"Opportunities: SUM: Amount","group_function":"sum","table_key":"self"},{"name":"opportunity_type","label":"Opportunities: Type","table_key":"self","is_group_by":"visible"},{"name":"name","label":"Team: Team Name","table_key":"self_link_0","is_group_by":"visible"}],"filters_def":[{"name":"sales_stage","table_key":"self","qualifier_name":"one_of","input_name0":["Prospecting","Qualification","Needs Analysis","Value Proposition","Id. Decision Makers","Perception Analysis","Proposal\/Price Quote","Negotiation\/Review"]}],"filters_combiner":"AND","group_defs":[{"name":"name","label":"Team Name","table_key":"self_link_0"},{"name":"opportunity_type","label":"Type","table_key":"self"}],"full_table_list":{"self":{"parent":"","value":"Opportunities","module":"Opportunities","label":"Opportunities","children":{"self_link_0":"self_link_0"}},"self_link_0":{"parent":"self","children":[],"value":"team_link","label":"Team","link_def":{"name":"team_link","relationship_name":"opportunities_team","bean_is_lhs":"","link_type":"one","label":"Team","table_key":"self_link_0"},"module":"Teams"}},"module":"Opportunities","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_11'] . '","chart_type":"hBarF","chart_description":"","numerical_chart_column":"self:amount_usdollar:sum","assigned_user_id":"1"}', 'summary','hBarF');
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_12'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"amount_usdollar","label":"Opportunities: SUM: Amount","group_function":"sum","table_key":"self"},{"name":"name","label":"Team: Team Name","table_key":"self_link_0","is_group_by":"visible"},{"name":"user_name","label":"Assigned to User: User Name","table_key":"self_link_1","is_group_by":"visible"}],"filters_def":[{"name":"sales_stage","table_key":"self","qualifier_name":"one_of","input_name0":["Prospecting","Qualification","Needs Analysis","Value Proposition","Id. Decision Makers","Perception Analysis","Proposal\/Price Quote","Negotiation\/Review"]}],"filters_combiner":"AND","group_defs":[{"name":"name","label":"Team Name","table_key":"self_link_0"},{"name":"user_name","label":"User Name","table_key":"self_link_1"}],"full_table_list":{"self":{"parent":"","value":"Opportunities","module":"Opportunities","label":"Opportunities","children":{"self_link_0":"self_link_0","self_link_1":"self_link_1"}},"self_link_0":{"parent":"self","children":[],"value":"team_link","label":"Team","link_def":{"name":"team_link","relationship_name":"opportunities_team","bean_is_lhs":"","link_type":"one","label":"Team","table_key":"self_link_0"},"module":"Teams"},"self_link_1":{"parent":"self","children":[],"value":"assigned_user_link","label":"Assigned to User","link_def":{"name":"assigned_user_link","relationship_name":"opportunities_assigned_user","bean_is_lhs":"","link_type":"one","label":"Assigned to User","table_key":"self_link_1"},"module":"Users"}},"module":"Opportunities","report_name":"' .$lang_strings['DEFAULT_REPORT_TITLE_12'] . '","chart_type":"hBarF","chart_description":"","numerical_chart_column":"self:amount_usdollar:sum","assigned_user_id":"1"}', 'summary','hBarF'); 
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_17'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"amount_usdollar","label":"Opportunities: SUM: Amount","group_function":"sum","table_key":"self"},{"name":"lead_source","label":"Opportunities: Lead Source","table_key":"self","is_group_by":"visible"},{"name":"count","label":"Count","group_function":"count","table_key":"self"}],"filters_def":[{"name":"sales_stage","table_key":"self","qualifier_name":"is","input_name0":["Closed Won"]}],"filters_combiner":"AND","group_defs":[{"name":"lead_source","label":"Lead Source","table_key":"self"}],"full_table_list":{"self":{"parent":"","value":"Opportunities","module":"Opportunities","label":"Opportunities","children":[]}},"module":"Opportunities","report_name":"' .$lang_strings['DEFAULT_REPORT_TITLE_17'] . '","chart_type":"hBarF","chart_description":"","numerical_chart_column":"self:amount_usdollar:sum","assigned_user_id":"1"}', 'summary','hBarF');
    // Activities
    $default_reports[] = array('Tasks', $lang_strings['DEFAULT_REPORT_TITLE_13'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"count","label":"Count","group_function":"count","table_key":"self"},{"name":"name","label":"Team: Team Name","table_key":"self_link_0","is_group_by":"visible"},{"name":"user_name","label":"Assigned to User: User Name","table_key":"self_link_1","is_group_by":"visible"}],"filters_def":[],"filters_combiner":"AND","group_defs":[{"name":"name","label":"Team Name","table_key":"self_link_0"},{"name":"user_name","label":"User Name","table_key":"self_link_1"}],"full_table_list":{"self":{"parent":"","value":"Tasks","module":"Tasks","label":"Tasks","children":{"self_link_0":"self_link_0","self_link_1":"self_link_1"}},"self_link_0":{"parent":"self","children":[],"value":"team_link","label":"Team","link_def":{"name":"team_link","relationship_name":"tasks_team","bean_is_lhs":"","link_type":"one","label":"Team","table_key":"self_link_0"},"module":"Teams"},"self_link_1":{"parent":"self","children":[],"value":"assigned_user_link","label":"Assigned to User","link_def":{"name":"assigned_user_link","relationship_name":"tasks_assigned_user","bean_is_lhs":"","link_type":"one","label":"Assigned to User","table_key":"self_link_1"},"module":"Users"}},"module":"Tasks","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_13'] . '","chart_type":"hBarF","chart_description":"","numerical_chart_column":"count","assigned_user_id":"1"}', 'summary','hBarF');
    $default_reports[] = array('Meetings', $lang_strings['DEFAULT_REPORT_TITLE_15'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"count","label":"Count","group_function":"count","table_key":"self"},{"name":"name","label":"Team: Team Name","table_key":"self_link_0","is_group_by":"visible"},{"name":"user_name","label":"Assigned to User: User Name","table_key":"self_link_1","is_group_by":"visible"}],"filters_def":[],"filters_combiner":"AND","group_defs":[{"name":"name","label":"Team Name","table_key":"self_link_0"},{"name":"user_name","label":"User Name","table_key":"self_link_1"}],"full_table_list":{"self":{"parent":"","value":"Meetings","module":"Meetings","label":"Meetings","children":{"self_link_0":"self_link_0","self_link_1":"self_link_1"}},"self_link_0":{"parent":"self","children":[],"value":"team_link","label":"Team","link_def":{"name":"team_link","relationship_name":"meetings_team","bean_is_lhs":"","link_type":"one","label":"Team","table_key":"self_link_0"},"module":"Teams"},"self_link_1":{"parent":"self","children":[],"value":"assigned_user_link","label":"Assigned to User","link_def":{"name":"assigned_user_link","relationship_name":"meetings_assigned_user","bean_is_lhs":"","link_type":"one","label":"Assigned to User","table_key":"self_link_1"},"module":"Users"}},"module":"Meetings","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_14'] . '","chart_type":"hBarF","chart_description":"","numerical_chart_column":"count","assigned_user_id":"1"}', 'summary','hBarF');
    $default_reports[] = array('Calls', $lang_strings['DEFAULT_REPORT_TITLE_14'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"count","label":"Count","group_function":"count","table_key":"self"},{"name":"name","label":"Team: Team Name","table_key":"self_link_0","is_group_by":"visible"},{"name":"user_name","label":"Assigned to User: User Name","table_key":"self_link_1","is_group_by":"visible"}],"filters_def":[],"filters_combiner":"AND","group_defs":[{"name":"name","label":"Team Name","table_key":"self_link_0"},{"name":"user_name","label":"User Name","table_key":"self_link_1"}],"full_table_list":{"self":{"parent":"","value":"Calls","module":"Calls","label":"Calls","children":{"self_link_0":"self_link_0","self_link_1":"self_link_1"}},"self_link_0":{"parent":"self","children":[],"value":"team_link","label":"Team","link_def":{"name":"team_link","relationship_name":"calls_team","bean_is_lhs":"","link_type":"one","label":"Team","table_key":"self_link_0"},"module":"Teams"},"self_link_1":{"parent":"self","children":[],"value":"assigned_user_link","label":"Assigned to User","link_def":{"name":"assigned_user_link","relationship_name":"calls_assigned_user","bean_is_lhs":"","link_type":"one","label":"Assigned to User","table_key":"self_link_1"},"module":"Users"}},"module":"Calls","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_15'] . '","chart_type":"hBarF","chart_description":"","numerical_chart_column":"count","assigned_user_id":"1"}', 'summary','hBarF');
    // Accounts
    $default_reports[] = array('Accounts', $lang_strings['DEFAULT_REPORT_TITLE_16'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"count","label":"Count","group_function":"count","table_key":"self"},{"name":"account_type","label":"Accounts: Type","table_key":"self","is_group_by":"visible"},{"name":"industry","label":"Accounts: Industry","table_key":"self","is_group_by":"visible"}],"filters_def":[],"filters_combiner":"AND","group_defs":[{"name":"account_type","label":"Type","table_key":"self"},{"name":"industry","label":"Industry","table_key":"self"}],"full_table_list":{"self":{"parent":"","value":"Accounts","module":"Accounts","label":"Accounts","children":[]}},"module":"Accounts","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_16'] . '","chart_type":"hBarF","chart_description":"","numerical_chart_column":"count","assigned_user_id":"1"}', 'summary', 'hBarF');
    // Leads
	$default_reports[] = array('Leads', $lang_strings['DEFAULT_REPORT_TITLE_18'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"count","label":"Count","group_function":"count","table_key":"self"},{"name":"lead_source","label":"Leads: Lead Source","table_key":"self","is_group_by":"visible"}],"filters_def":[],"filters_combiner":"AND","group_defs":[{"name":"lead_source","label":"Lead Source","table_key":"self"}],"full_table_list":{"self":{"parent":"","value":"Leads","module":"Leads","label":"Leads","children":{"self_link_0":"self_link_0"}},"self_link_0":{"parent":"self","children":[],"value":"assigned_user_link","label":"Assigned To User","link_def":{"name":"assigned_user_link","relationship_name":"leads_assigned_user","bean_is_lhs":"","link_type":"one","label":"Assigned To User","table_key":"self_link_0"},"module":"Users"}},"module":"Leads","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_18'] . '","chart_type":"vBarF","chart_description":"","numerical_chart_column":"count","assigned_user_id":"1"}', 'summary', 'vBarF');

	
	
	
    $default_reports[] = array('Accounts', $lang_strings['DEFAULT_REPORT_TITLE_43'], '{"display_columns":[{"name":"name","label":"Name","table_key":"self"},{"name":"website","label":"Website","table_key":"self"},{"name":"phone_office","label":"Phone Office","table_key":"self"},{"name":"billing_address_city","label":"Billing City","table_key":"self"},{"name":"billing_address_country","label":"Billing Country","table_key":"self"}],"module":"Accounts","group_defs":[{"name":"user_name","label":"User Name","table_key":"Accounts:assigned_user_link","type":"user_name"}],"summary_columns":[{"name":"user_name","label":"User Name","table_key":"Accounts:assigned_user_link"},{"name":"count","label":"Count","field_type":"","group_function":"count","table_key":"self"}],"order_by":[{"name":"name","type":"name","dbType":"varchar","vname":"Name","len":"150","unified_search":"1","audited":"1","required":"1","importable":"required","merge_filter":"selected","table_key":"self","sort_dir":"a"}],"report_name":"Customer Account Owners","chart_type":"none","do_round":1,"chart_description":"Customer Account Owners","numerical_chart_column":"self:count","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"summary","full_table_list":{"self":{"value":"Accounts","module":"Accounts","label":"Accounts"},"Accounts:assigned_user_link":{"name":"Accounts > Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"accounts_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Accounts:assigned_user_link"},"dependents":["Filter.1_table_filter_row_1","group_by_row_1","display_summaries_row_group_by_row_1","Filter.1_table_filter_row_1","group_by_row_1","display_summaries_row_group_by_row_1"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"user_name","table_key":"Accounts:assigned_user_link","qualifier_name":"one_of","runtime":1,"input_name0":["Current User"]}}}}', 'summary', 'none');
    $default_reports[] = array('Accounts', $lang_strings['DEFAULT_REPORT_TITLE_44'], '{"display_columns":[{"name":"name","label":"Name","table_key":"self"},{"name":"website","label":"Website","table_key":"self"},{"name":"phone_office","label":"Phone Office","table_key":"self"},{"name":"billing_address_city","label":"Billing City","table_key":"self"},{"name":"billing_address_country","label":"Billing Country","table_key":"self"}],"module":"Accounts","group_defs":[],"summary_columns":[],"report_name":"My New Customer Accounts","do_round":1,"numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"tabular","full_table_list":{"self":{"value":"Accounts","module":"Accounts","label":"Accounts"},"Accounts:assigned_user_link":{"name":"Accounts  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"accounts_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Accounts:assigned_user_link"},"dependents":["Filter.1_table_filter_row_2"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"account_type","table_key":"self","qualifier_name":"is","input_name0":["Customer"]},"1":{"name":"user_name","table_key":"Accounts:assigned_user_link","qualifier_name":"is","input_name0":["Current User"]},"2":{"name":"date_entered","table_key":"self","qualifier_name":"tp_last_7_days","runtime":1,"input_name0":"undefined","input_name1":"on"}}},"chart_type":"none"}', 'tabular');
    
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_45'], '{"display_columns":[{"name":"name","label":"Opportunity Name","table_key":"self"},{"name":"amount_usdollar","label":"Amount","table_key":"self"},{"name":"date_closed","label":"Expected Close Date","table_key":"self"},{"name":"description","label":"Description","table_key":"self"},{"name":"opportunity_type","label":"Type","table_key":"self"},{"name":"probability","label":"Probability (%)","table_key":"self"},{"name":"user_name","label":"User Name","table_key":"Opportunities:assigned_user_link"}],"module":"Opportunities","group_defs":[{"name":"sales_stage","label":"Sales Stage","table_key":"self","type":"enum"}],"summary_columns":[{"name":"sales_stage","label":"Sales Stage","table_key":"self"},{"name":"count","label":"Count","field_type":"","group_function":"count","table_key":"self"},{"name":"amount_usdollar","label":"AVG: Amount","field_type":"currency","group_function":"avg","table_key":"self"},{"name":"amount_usdollar","label":"SUM: Amount","field_type":"currency","group_function":"sum","table_key":"self"}],"order_by":[{"name":"date_closed","label":"Expected Close Date","table_key":"self","sort_dir":"a"}],"report_name":"Opportunities By Stage","chart_type":"none","do_round":1,"chart_description":"Opportunities By Stage","numerical_chart_column":"self:count","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"summary","full_table_list":{"self":{"value":"Opportunities","module":"Opportunities","label":"Opportunities"},"Opportunities:assigned_user_link":{"name":"Opportunities  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"opportunities_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Opportunities:assigned_user_link"},"dependents":["display_cols_row_11","Filter.1_table_filter_row_2"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"sales_stage","table_key":"self","qualifier_name":"one_of","runtime":1,"input_name0":["Prospecting","Qualification","Needs Analysis","Value Proposition","Id. Decision Makers","Perception Analysis","Proposal\/Price Quote","Negotiation\/Review","Closed Won","Closed Lost"],"column_name":"self:sales_stage","id":"rowid0"},"1":{"name":"user_name","table_key":"Opportunities:assigned_user_link","qualifier_name":"one_of","runtime":1,"input_name0":["1","seed_chris_id","seed_jim_id","seed_max_id","seed_sally_id","seed_sarah_id","seed_will_id"],"column_name":"Opportunities:assigned_user_link:user_name","id":"rowid1"}}}}', 'summary', 'none');
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_46'], '{"display_columns":[{"name":"name","label":"Opportunity Name","table_key":"self"},{"name":"amount_usdollar","label":"Amount","table_key":"self"},{"name":"date_closed","label":"Expected Close Date","table_key":"self"},{"name":"sales_stage","label":"Sales Stage","table_key":"self"},{"name":"description","label":"Description","table_key":"self"},{"name":"user_name","label":"User Name","table_key":"Opportunities:assigned_user_link"}],"module":"Opportunities","group_defs":[{"name":"opportunity_type","label":"Type","table_key":"self","type":"enum"},{"name":"sales_stage","label":"Sales Stage","table_key":"self","type":"enum"}],"summary_columns":[{"name":"opportunity_type","label":"Type","table_key":"self"},{"name":"sales_stage","label":"Sales Stage","table_key":"self"},{"name":"count","label":"Count","field_type":"","group_function":"count","table_key":"self"},{"name":"amount_usdollar","label":"AVG: Amount","field_type":"currency","group_function":"avg","table_key":"self"},{"name":"amount_usdollar","label":"SUM: Amount","field_type":"currency","group_function":"sum","table_key":"self"}],"report_name":"Opportunities By Type","chart_type":"none","do_round":1,"chart_description":"Opportunities By Type","numerical_chart_column":"self:count","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"summary","full_table_list":{"self":{"value":"Opportunities","module":"Opportunities","label":"Opportunities"},"Opportunities:assigned_user_link":{"name":"Opportunities  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"opportunities_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Opportunities:assigned_user_link"},"dependents":["Filter.1_table_filter_row_3","display_cols_row_12"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"opportunity_type","table_key":"self","qualifier_name":"one_of","runtime":1,"input_name0":["Existing Business","New Business"]},"1":{"name":"sales_stage","table_key":"self","qualifier_name":"one_of","runtime":1,"input_name0":["Prospecting","Qualification","Needs Analysis","Value Proposition","Id. Decision Makers","Perception Analysis","Proposal\/Price Quote","Negotiation\/Review","Closed Won","Closed Lost"]},"2":{"name":"user_name","table_key":"Opportunities:assigned_user_link","qualifier_name":"one_of","runtime":1,"input_name0":["Current User","1","seed_chris_id","seed_jim_id","seed_max_id","seed_sally_id","seed_sarah_id","seed_will_id"]}}}}', 'summary', 'none');    

    $default_reports[] = array('Calls', $lang_strings['DEFAULT_REPORT_TITLE_47'], '{"display_columns":[{"name":"name","label":"Subject","table_key":"self"},{"name":"status","label":"Status","table_key":"self"},{"name":"date_entered","label":"Date Created","table_key":"self"},{"name":"user_name","label":"User Name","table_key":"Calls:assigned_user_link"}],"module":"Calls","group_defs":[],"summary_columns":[],"order_by":[{"name":"date_entered","vname":"Date Created","type":"datetime","group":"created_by_name","table_key":"self","sort_dir":"a"}],"report_name":"Open Calls","do_round":1,"numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"tabular","full_table_list":{"self":{"value":"Calls","module":"Calls","label":"Calls"},"Calls:assigned_user_link":{"name":"Calls  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"calls_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Calls:assigned_user_link"},"dependents":["display_cols_row_4","Filter.1_table_filter_row_3"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"status","table_key":"self","qualifier_name":"one_of","runtime":1,"input_name0":["Planned","Not Held"]},"1":{"name":"date_start","table_key":"self","qualifier_name":"tp_last_7_days","runtime":1,"input_name0":"undefined","input_name1":"on"},"2":{"name":"user_name","table_key":"Calls:assigned_user_link","qualifier_name":"one_of","runtime":1,"input_name0":["Current User"]}}},"chart_type":"none"}', 'tabular');
    $default_reports[] = array('Meetings', $lang_strings['DEFAULT_REPORT_TITLE_48'], '{"display_columns":[{"name":"name","label":"Subject","table_key":"self"},{"name":"description","label":"Description","table_key":"self"},{"name":"date_entered","label":"Date Created","table_key":"self"},{"name":"user_name","label":"User Name","table_key":"Meetings:assigned_user_link"}],"module":"Meetings","group_defs":[],"summary_columns":[],"order_by":[{"name":"date_entered","vname":"Date Created","type":"datetime","group":"created_by_name","table_key":"self","sort_dir":"a"}],"report_name":"Open Meetings","do_round":1,"numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"tabular","full_table_list":{"self":{"value":"Meetings","module":"Meetings","label":"Meetings"},"Meetings:assigned_user_link":{"name":"Meetings  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"meetings_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Meetings:assigned_user_link"},"dependents":["Filter.1_table_filter_row_3","display_cols_row_4"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"status","table_key":"self","qualifier_name":"one_of","runtime":1,"input_name0":["Planned","Not Held"]},"1":{"name":"date_start","table_key":"self","qualifier_name":"tp_last_7_days","runtime":1,"input_name0":"undefined","input_name1":"on"},"2":{"name":"user_name","table_key":"Meetings:assigned_user_link","qualifier_name":"one_of","runtime":1,"input_name0":["Current User"]}}},"chart_type":"none"}', 'tabular');
    $default_reports[] = array('Tasks', $lang_strings['DEFAULT_REPORT_TITLE_49'], '{"display_columns":[{"name":"name","label":"Subject","table_key":"self"},{"name":"priority","label":"Priority","table_key":"self"},{"name":"status","label":"Status","table_key":"self"},{"name":"date_entered","label":"Date Created","table_key":"self"},{"name":"date_due","label":"Due Date","table_key":"self"},{"name":"user_name","label":"User Name","table_key":"Tasks:assigned_user_link"}],"module":"Tasks","group_defs":[],"summary_columns":[],"order_by":[{"name":"date_due","vname":"Due Date","type":"datetime","group":"date_due","table_key":"self","sort_dir":"d"}],"report_name":"Open Tasks","do_round":1,"numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"tabular","full_table_list":{"self":{"value":"Tasks","module":"Tasks","label":"Tasks"},"Tasks:assigned_user_link":{"name":"Tasks  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tasks_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Tasks:assigned_user_link"},"dependents":["Filter.1_table_filter_row_4","display_cols_row_6"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"status","table_key":"self","qualifier_name":"one_of","runtime":1,"input_name0":["Not Started","In Progress","Pending Input"]},"1":{"name":"date_entered","table_key":"self","qualifier_name":"tp_last_7_days","runtime":1,"input_name0":"undefined","input_name1":"on"},"2":{"name":"user_name","table_key":"Tasks:assigned_user_link","qualifier_name":"one_of","runtime":1,"input_name0":["Current User"]}}},"chart_type":"none"}', 'tabular');
 
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_50'], '{"display_columns":[{"name":"name","label":"Opportunity Name","table_key":"self"},{"name":"name","label":"Account Name","table_key":"Opportunities:accounts"},{"name":"date_closed","label":"Expected Close Date","table_key":"self"}],"module":"Opportunities","group_defs":[{"name":"name","label":"Account Name","table_key":"Opportunities:accounts","type":"name"}],"summary_columns":[{"name":"name","label":"Account Name","table_key":"Opportunities:accounts"}],"report_name":"Opportunities Won By Account","chart_type":"none","do_round":1,"chart_description":"Opportunities Won By Account","numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"summary","order_by":[{"name":"date_closed","vname":"Expected Close Date","type":"date","audited":"1","importable":"required","table_key":"self","sort_dir":"a"}],"full_table_list":{"self":{"value":"Opportunities","module":"Opportunities","label":"Opportunities"},"Opportunities:accounts":{"name":"Opportunities  >  Accounts","parent":"self","link_def":{"name":"accounts","relationship_name":"accounts_opportunities","bean_is_lhs":false,"link_type":"one","label":"Accounts","table_key":"Opportunities:accounts"},"dependents":["group_by_row_1","display_summaries_row_group_by_row_1","display_cols_row_3","group_by_row_1","display_summaries_row_group_by_row_1","display_cols_row_3","group_by_row_1","display_summaries_row_group_by_row_1","display_cols_row_3","Filter.1_table_filter_row_4","Filter.1_table_filter_row_2","group_by_row_1","display_summaries_row_group_by_row_1","display_cols_row_3"],"module":"Accounts","label":"Accounts"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"sales_stage","table_key":"self","qualifier_name":"is","runtime":1,"input_name0":["Closed Won"]},"1":{"name":"name","table_key":"Opportunities:accounts","qualifier_name":"not_empty","runtime":1,"input_name0":"not_empty","input_name1":"on"},"2":{"name":"date_closed","table_key":"self","qualifier_name":"not_empty","runtime":1,"input_name0":"not_empty","input_name1":"on"}}}}', 'detailed_summary', 'none');
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_51'], '{"display_columns":[{"name":"name","label":"Opportunity Name","table_key":"self"},{"name":"date_closed","label":"Expected Close Date","table_key":"self"}],"module":"Opportunities","group_defs":[{"name":"user_name","label":"User Name","table_key":"Opportunities:assigned_user_link","type":"user_name"}],"summary_columns":[{"name":"user_name","label":"User Name","table_key":"Opportunities:assigned_user_link"}],"order_by":[{"name":"date_closed","vname":"Expected Close Date","type":"date","audited":"1","importable":"required","table_key":"self","sort_dir":"a"}],"report_name":"Opportunities Won By User","chart_type":"none","do_round":1,"chart_description":"","numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"summary","full_table_list":{"self":{"value":"Opportunities","module":"Opportunities","label":"Opportunities"},"Opportunities:assigned_user_link":{"name":"Opportunities  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"opportunities_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Opportunities:assigned_user_link"},"dependents":["Filter.1_table_filter_row_2","group_by_row_1","display_summaries_row_group_by_row_1"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"sales_stage","table_key":"self","qualifier_name":"is","input_name0":["Closed Won"]},"1":{"name":"user_name","table_key":"Opportunities:assigned_user_link","qualifier_name":"one_of","runtime":1,"input_name0":["Current User","1","seed_chris_id","seed_jim_id","seed_max_id","seed_sally_id","seed_sarah_id","seed_will_id"]},"2":{"name":"date_closed","table_key":"self","qualifier_name":"not_empty","runtime":1,"input_name0":"undefined","input_name1":"on"}}}}', 'detailed_summary', 'none');
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_52'], '{"display_columns":[{"name":"name","label":"Opportunity Name","table_key":"self"},{"name":"opportunity_type","label":"Type","table_key":"self"},{"name":"sales_stage","label":"Sales Stage","table_key":"self"},{"name":"date_closed","label":"Expected Close Date","table_key":"self"},{"name":"amount_usdollar","label":"Amount","table_key":"self"},{"name":"user_name","label":"User Name","table_key":"Opportunities:assigned_user_link"}],"module":"Opportunities","group_defs":[],"summary_columns":[],"order_by":[{"name":"date_closed","vname":"Expected Close Date","type":"date","audited":"1","importable":"required","table_key":"self","sort_dir":"a"}],"report_name":"All Open Opportunities","chart_type":"none","do_round":1,"numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"tabular","full_table_list":{"self":{"value":"Opportunities","module":"Opportunities","label":"Opportunities"},"Opportunities:assigned_user_link":{"name":"Opportunities  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"opportunities_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Opportunities:assigned_user_link"},"dependents":["display_cols_row_6","display_cols_row_6"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"sales_stage","table_key":"self","qualifier_name":"one_of","runtime":1,"input_name0":["Prospecting","Qualification","Needs Analysis","Value Proposition","Id. Decision Makers","Perception Analysis","Proposal\/Price Quote","Negotiation\/Review"]},"1":{"name":"date_closed","table_key":"self","qualifier_name":"not_empty","runtime":1,"input_name0":"undefined","input_name1":"on"}}}}', 'tabular');
    $default_reports[] = array('Opportunities', $lang_strings['DEFAULT_REPORT_TITLE_53'], '{"display_columns":[{"name":"name","label":"Opportunity Name","table_key":"self"},{"name":"opportunity_type","label":"Type","table_key":"self"},{"name":"sales_stage","label":"Sales Stage","table_key":"self"},{"name":"date_closed","label":"Expected Close Date","table_key":"self"},{"name":"amount_usdollar","label":"Amount","table_key":"self"},{"name":"user_name","label":"User Name","table_key":"Opportunities:assigned_user_link"}],"module":"Opportunities","group_defs":[],"summary_columns":[],"order_by":[{"name":"date_closed","vname":"Expected Close Date","type":"date","audited":"1","importable":"required","table_key":"self","sort_dir":"a"}],"report_name":"All Closed Opportunities","do_round":1,"numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"tabular","full_table_list":{"self":{"value":"Opportunities","module":"Opportunities","label":"Opportunities"},"Opportunities:assigned_user_link":{"name":"Opportunities  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"opportunities_assigned_user","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Opportunities:assigned_user_link"},"dependents":["display_cols_row_8"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"sales_stage","table_key":"self","qualifier_name":"one_of","runtime":1,"input_name0":["Closed Won","Closed Lost"]},"1":{"name":"date_closed","table_key":"self","qualifier_name":"not_empty","runtime":1,"input_name0":"undefined","input_name1":"on"}}},"chart_type":"none"}', 'tabular');

    // Trackers
    // My Usage Metrics (Today)
    $default_reports[] = array('TrackerPerfs', $lang_strings['DEFAULT_REPORT_TITLE_19'], '{"display_columns":[],"module":"Trackers","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_19'] . '","group_defs":[],"summary_columns":[{"name":"server_response_time","label":"Total Server Response Time (secs)","group_function":"sum","table_key":"Trackers:tracker_monitor_id"},{"name":"db_round_trips","label":"Total Database Roundtrips","group_function":"sum","table_key":"Trackers:tracker_monitor_id"},{"name":"files_opened","label":"Total Files Accessed","group_function":"sum","table_key":"Trackers:tracker_monitor_id"}],"chart_type":"none","chart_description":"' . $lang_strings['DEFAULT_REPORT_TITLE_19'] . '","numerical_chart_column":"Trackers>tracker_monitor_id->server_response_time","report_type":"summary","full_table_list":{"self":{"value":"Trackers","module":"Trackers","label":"Trackers"},"Trackers:tracker_user_id":{"name":"Trackers  >  Assigned to User","label":"Users","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Trackers:tracker_user_id"},"dependents":["Filter_1_table_filter_row_1"],"module":"Users"},"Trackers:tracker_monitor_id":{"name":"Trackers  >  Monitor Id","label":"TrackerPerfs","parent":"self","link_def":{"name":"monitor_id_link","relationship_name":"tracker_monitor_id","bean_is_lhs":false,"link_type":"one","label":"Monitor Id","table_key":"Trackers:tracker_monitor_id"},"dependents":["display_summaries_row_1","display_summaries_row_2","display_summaries_row_3"],"module":"TrackerPerfs"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"user_name","table_key":"Trackers:tracker_user_id","qualifier_name":"is","input_name0":["Current User"]},"1":{"name":"date_modified","table_key":"self","qualifier_name":"tp_today","input_name0":"tp_today"}}}}', 'summary', 'none');
    
    // My Usage Metrics (Last Seven Days)
    $default_reports[] = array('TrackerPerfs', $lang_strings['DEFAULT_REPORT_TITLE_20'], '{"display_columns":[],"module":"Trackers","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_20'] . '","group_defs":[],"summary_columns":[{"name":"server_response_time","label":"Total Server Response Time (secs)","group_function":"sum","table_key":"Trackers:tracker_monitor_id"},{"name":"db_round_trips","label":"Total Database Roundtrips","group_function":"sum","table_key":"Trackers:tracker_monitor_id"},{"name":"files_opened","label":"Total Files Accessed","group_function":"sum","table_key":"Trackers:tracker_monitor_id"}],"chart_type":"none","chart_description":"' . $lang_strings['DEFAULT_REPORT_TITLE_20'] . '","numerical_chart_column":"Trackers>tracker_monitor_id->server_response_time","report_type":"summary","full_table_list":{"self":{"value":"Trackers","module":"Trackers","label":"Trackers"},"Trackers:tracker_user_id":{"name":"Trackers  >  Assigned to User","label":"Users","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Trackers:tracker_user_id"},"dependents":["Filter_1_table_filter_row_1"],"module":"Users"},"Trackers:tracker_monitor_id":{"name":"Trackers  >  Monitor Id","label":"TrackerPerfs","parent":"self","link_def":{"name":"monitor_id_link","relationship_name":"tracker_monitor_id","bean_is_lhs":false,"link_type":"one","label":"Monitor Id","table_key":"Trackers:tracker_monitor_id"},"dependents":["display_summaries_row_1","display_summaries_row_2","display_summaries_row_3"],"module":"TrackerPerfs"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"user_name","table_key":"Trackers:tracker_user_id","qualifier_name":"is","input_name0":["Current User"]},"1":{"name":"date_modified","table_key":"self","qualifier_name":"tp_last_7_days","input_name0":"tp_last_7_days"}}}}', 'summary', 'none');

    // My Usage Metrics (Last 30 Days)
    $default_reports[] = array('TrackerPerfs', $lang_strings['DEFAULT_REPORT_TITLE_21'], '{"display_columns":[],"module":"Trackers","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_21'] . '","group_defs":[],"summary_columns":[{"name":"server_response_time","label":"Total Server Response Time (secs)","group_function":"sum","table_key":"Trackers:tracker_monitor_id"},{"name":"db_round_trips","label":"Total Database Roundtrips","group_function":"sum","table_key":"Trackers:tracker_monitor_id"},{"name":"files_opened","label":"Total Files Accessed","group_function":"sum","table_key":"Trackers:tracker_monitor_id"}],"chart_type":"none","chart_description":"' . $lang_strings['DEFAULT_REPORT_TITLE_21'] . '","numerical_chart_column":"Trackers>tracker_monitor_id->server_response_time","report_type":"summary","full_table_list":{"self":{"value":"Trackers","module":"Trackers","label":"Trackers"},"Trackers:tracker_user_id":{"name":"Trackers  >  Assigned to User","label":"Users","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Trackers:tracker_user_id"},"dependents":["Filter_1_table_filter_row_1"],"module":"Users"},"Trackers:tracker_monitor_id":{"name":"Trackers  >  Monitor Id","label":"TrackerPerfs","parent":"self","link_def":{"name":"monitor_id_link","relationship_name":"tracker_monitor_id","bean_is_lhs":false,"link_type":"one","label":"Monitor Id","table_key":"Trackers:tracker_monitor_id"},"dependents":["display_summaries_row_1","display_summaries_row_2","display_summaries_row_3"],"module":"TrackerPerfs"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"user_name","table_key":"Trackers:tracker_user_id","qualifier_name":"is","input_name0":["Current User"]},"1":{"name":"date_modified","table_key":"self","qualifier_name":"tp_last_30_days","input_name0":"tp_last_30_days"}}}}', 'summary', 'none');

    // My Module Usage (Today)
    $default_reports[] = array('Trackers', $lang_strings['DEFAULT_REPORT_TITLE_22'], '{"display_columns":[],"module":"Trackers","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_22'] . '","group_defs":[{"name":"module_name","label":"Module Name","table_key":"self"}],"summary_columns":[{"name":"module_name","label":"Trackers > Module Name","table_key":"self"},{"name":"count","label":"Trackers > Count","group_function":"count","table_key":"self"}],"chart_type":"hBarF","chart_description":"'.$lang_strings['DEFAULT_REPORT_TITLE_22'] . '","numerical_chart_column":"count","report_type":"summary","full_table_list":{"self":{"value":"Trackers","module":"Trackers","label":"Trackers"},"Trackers:tracker_user_id":{"name":"Trackers  >  Assigned to User","label":"Users","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Trackers:tracker_user_id"},"dependents":["Filter_1_table_filter_row_1"],"module":"Users"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"user_name","table_key":"Trackers:tracker_user_id","qualifier_name":"is","input_name0":["Current User"]},"1":{"name":"date_modified","table_key":"self","qualifier_name":"tp_today","input_name0":"tp_today"}}}}', 'summary', 'hBarF');

    // My Module Usage (Last Seven Days)
    $default_reports[] = array('Trackers', $lang_strings['DEFAULT_REPORT_TITLE_23'], '{"display_columns":[],"module":"Trackers","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_23'] . '","group_defs":[{"name":"module_name","label":"Module Name","table_key":"self"}],"summary_columns":[{"name":"module_name","label":"Trackers > Module Name","table_key":"self"},{"name":"count","label":"Trackers > Count","group_function":"count","table_key":"self"}],"chart_type":"hBarF","chart_description":"'.$lang_strings['DEFAULT_REPORT_TITLE_23'] . '","numerical_chart_column":"count","report_type":"summary","full_table_list":{"self":{"value":"Trackers","module":"Trackers","label":"Trackers"},"Trackers:tracker_user_id":{"name":"Trackers  >  Assigned to User","label":"Users","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Trackers:tracker_user_id"},"dependents":["Filter_1_table_filter_row_1"],"module":"Users"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"user_name","table_key":"Trackers:tracker_user_id","qualifier_name":"is","input_name0":["Current User"]},"1":{"name":"date_modified","table_key":"self","qualifier_name":"tp_last_7_days","input_name0":"tp_last_7_days"}}}}', 'summary', 'hBarF');

    // My Module Usage (Last 30 Days)
    $default_reports[] = array('Trackers', $lang_strings['DEFAULT_REPORT_TITLE_24'], '{"display_columns":[],"module":"Trackers","report_name":"'. $lang_strings['DEFAULT_REPORT_TITLE_24'] .'","group_defs":[{"name":"module_name","label":"Module Name","table_key":"self"}],"summary_columns":[{"name":"module_name","label":"Trackers > Module Name","table_key":"self"},{"name":"count","label":"Trackers > Count","group_function":"count","table_key":"self"}],"chart_type":"hBarF","chart_description":"' . $lang_strings['DEFAULT_REPORT_TITLE_24'] . '","numerical_chart_column":"count","report_type":"summary","full_table_list":{"self":{"value":"Trackers","module":"Trackers","label":"Trackers"},"Trackers:tracker_user_id":{"name":"Trackers  >  Assigned to User","label":"Users","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Trackers:tracker_user_id"},"dependents":["Filter_1_table_filter_row_1"],"module":"Users"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"user_name","table_key":"Trackers:tracker_user_id","qualifier_name":"is","input_name0":["Current User"]},"1":{"name":"date_modified","table_key":"self","qualifier_name":"tp_last_30_days","input_name0":"tp_last_30_days"}}}}', 'summary', 'hBarF');

    // Users Usage Metrics (Last 7 Days)
    $default_reports[] = array('TrackerPerfs', $lang_strings['DEFAULT_REPORT_TITLE_25'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"user_id","label":"User Id","table_key":"self","is_group_by":"visible"},{"name":"server_response_time","label":"Total Server Response Time (secs)","group_function":"sum","table_key":"self_link_0"},{"name":"db_round_trips","label":"Total Database Roundtrips","group_function":"sum","table_key":"self_link_0"},{"name":"files_opened","label":"Total Files Accessed","group_function":"sum","table_key":"self_link_0"}],"filters_def":[{"name":"date_modified","table_key":"self","qualifier_name":"tp_last_7_days","input_name0":"tp_last_7_days"}],"filters_combiner":"AND","group_defs":[{"name":"user_id","label":"User Id","table_key":"self"}],"full_table_list":{"self":{"parent":"","value":"Trackers","module":"Trackers","label":"Tracker","children":[]},"self_link_0":{"parent":"self","children":[],"value":"monitor_id_link","label":"Monitor Id","link_def":{"name":"monitor_id_link","relationship_name":"tracker_monitor_id","bean_is_lhs":false,"link_type":"one","label":"Monitor Id","table_key":"self_link_0"},"module":"TrackerPerfs"}},"module":"Trackers","report_name":"'. $lang_strings['DEFAULT_REPORT_TITLE_25'] .'","chart_type":"none","chart_description":"'. $lang_strings['DEFAULT_REPORT_TITLE_25'] .'","numerical_chart_column":"self_link_0:server_response_time:sum","assigned_user_id":"1"}', 'summary', 'none');
    
    // Users Usage Metrics (Last 30 Days)
    $default_reports[] = array('TrackerPerfs', $lang_strings['DEFAULT_REPORT_TITLE_26'], '{"report_type":"summary","display_columns":[],"summary_columns":[{"name":"user_id","label":"User Id","table_key":"self","is_group_by":"visible"},{"name":"server_response_time","label":"Total Server Response Time (secs)","group_function":"sum","table_key":"self_link_0"},{"name":"db_round_trips","label":"Total Database Roundtrips","group_function":"sum","table_key":"self_link_0"},{"name":"files_opened","label":"Total Files Accessed","group_function":"sum","table_key":"self_link_0"}],"filters_def":[{"name":"date_modified","table_key":"self","qualifier_name":"tp_last_30_days","input_name0":"tp_last_30_days"}],"filters_combiner":"AND","group_defs":[{"name":"user_id","label":"User Id","table_key":"self"}],"full_table_list":{"self":{"parent":"","value":"Trackers","module":"Trackers","label":"Tracker","children":[]},"self_link_0":{"parent":"self","children":[],"value":"monitor_id_link","label":"Monitor Id","link_def":{"name":"monitor_id_link","relationship_name":"tracker_monitor_id","bean_is_lhs":false,"link_type":"one","label":"Monitor Id","table_key":"self_link_0"},"module":"TrackerPerfs"}},"module":"Trackers","report_name":"'. $lang_strings['DEFAULT_REPORT_TITLE_26'] .'","chart_type":"none","chart_description":"'. $lang_strings['DEFAULT_REPORT_TITLE_26'] .'","numerical_chart_column":"self_link_0:server_response_time:sum","assigned_user_id":"1"}', 'summary', 'none');
    
    // Modules Used By My Direct Reports (Last 30 Days)
    $default_reports[] = array('Trackers', $lang_strings['DEFAULT_REPORT_TITLE_27'], '{"display_columns":[],"module":"Trackers","group_defs":[{"name":"module_name","label":"Module Name","table_key":"self","type":"varchar"}],"summary_columns":[{"name":"module_name","label":"Module Name","table_key":"self"},{"name":"count","label":"Count","field_type":"","group_function":"count","table_key":"self"}],"report_name":"'.$lang_strings['DEFAULT_REPORT_TITLE_27'].'","chart_type":"hBarF","chart_description":"","numerical_chart_column":"self:count","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"summary","full_table_list":{"self":{"value":"Trackers","module":"Trackers","label":"Trackers"},"Trackers:assigned_user_link":{"name":"Trackers  >  Assigned to User ","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Trackers:assigned_user_link"},"dependents":["Filter.1_table_filter_row_3"],"module":"Users","label":"Assigned to User"},"Trackers:assigned_user_link:reports_to_link":{"name":"Trackers  >  Assigned to User  >  Reports To","parent":"Trackers:assigned_user_link","link_def":{"name":"reports_to_link","relationship_name":"user_direct_reports","bean_is_lhs":false,"link_type":"one","label":"Reports to","table_key":"Trackers:assigned_user_link:reports_to_link"},"dependents":["Filter.1_table_filter_row_3"],"module":"Users","label":"Reports to"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"module_name","table_key":"self","qualifier_name":"not_equals_str","input_name0":"UserPreferences","input_name1":"on"},"1":{"name":"date_modified","table_key":"self","qualifier_name":"tp_last_30_days","input_name0":"undefined","input_name1":"on"},"2":{"name":"user_name","table_key":"Trackers:assigned_user_link:reports_to_link","qualifier_name":"one_of","input_name0":["Current User"]}}}}', 'summary','hBarF');
    
    // Slow Queries
    $default_reports[] = array('TrackerQueries', $lang_strings['DEFAULT_REPORT_TITLE_28'], '{"report_type":"tabular","display_columns":[{"name":"text","label":"SQL STATEMENT","table_key":"self"},{"name":"sec_avg","label":"Average Seconds","table_key":"self"},{"name":"sec_total","label":"Seconds Total","table_key":"self"},{"name":"run_count","label":"Execution Count","table_key":"self"}],"summary_columns":[],"filters_def":[],"filters_combiner":"AND","group_defs":[],"full_table_list":{"self":{"parent":"","value":"TrackerQueries","module":"TrackerQueries","label":"Tracker Queries","children":[]}},"module":"TrackerQueries","report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_28'] . '","chart_type":"none","chart_description":"","numerical_chart_column":"count","assigned_user_id":"1"}', 'tabular');

    // My Records Modified (Last 7 Days)
    $default_reports[] = array('Trackers', $lang_strings['DEFAULT_REPORT_TITLE_29'], '{"display_columns":[{"name":"item_id","label":"Trackers > Item Id","table_key":"self"},{"name":"item_summary","label":"Trackers > Item Summary","table_key":"self"},{"name":"module_name","label":"Trackers > Module Name","table_key":"self"},{"name":"action","label":"Trackers > Action","table_key":"self"},{"name":"date_modified","label":"Trackers > Last Modified","table_key":"self"}],"module":"Trackers","report_name":"'. $lang_strings['DEFAULT_REPORT_TITLE_29'] . '","group_defs":[],"summary_columns":[],"chart_type":"none","numerical_chart_column":"","report_type":"tabular","full_table_list":{"self":{"value":"Trackers","module":"Trackers","label":"Trackers"},"Trackers:tracker_user_id":{"name":"Trackers  >  Assigned to User","label":"Users","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Trackers:tracker_user_id"},"dependents":["Filter_1_table_filter_row_1"],"module":"Users"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"user_name","table_key":"Trackers:tracker_user_id","qualifier_name":"is","input_name0":["Current User"]},"1":{"name":"action","table_key":"self","qualifier_name":"equals","input_name0":"save","input_name1":"on"},"2":{"name":"date_modified","table_key":"self","qualifier_name":"tp_last_7_days","input_name0":"tp_last_7_days"}}}}', 'tabular');
    
    // My Recently Modified Records (Last 30 Days)
    $default_reports[] = array('Trackers', $lang_strings['DEFAULT_REPORT_TITLE_31'], '{"display_columns":[{"name":"item_id","label":"Trackers > Item Id","table_key":"self"},{"name":"item_summary","label":"Trackers > Item Summary","table_key":"self"},{"name":"module_name","label":"Trackers > Module Name","table_key":"self"},{"name":"action","label":"Trackers > Action","table_key":"self"},{"name":"date_modified","label":"Trackers > Last Modified","table_key":"self"}],"module":"Trackers","report_name":"'.$lang_strings['DEFAULT_REPORT_TITLE_31'].'","group_defs":[],"summary_columns":[],"chart_type":"none","numerical_chart_column":"","report_type":"tabular","full_table_list":{"self":{"value":"Trackers","module":"Trackers","label":"Trackers"},"Trackers:tracker_user_id":{"name":"Trackers  >  Assigned to User","label":"Users","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Trackers:tracker_user_id"},"dependents":["Filter_1_table_filter_row_1"],"module":"Users"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"user_name","table_key":"Trackers:tracker_user_id","qualifier_name":"is","input_name0":["Current User"]},"1":{"name":"action","table_key":"self","qualifier_name":"equals","input_name0":"save","input_name1":"on"},"2":{"name":"date_modified","table_key":"self","qualifier_name":"tp_last_30_days","input_name0":"tp_last_30_days"}}}}', 'tabular');
 
    // My Direct Report's Recently Modified Records (Last 30 Days)
    $default_reports[] = array('Trackers', $lang_strings['DEFAULT_REPORT_TITLE_32'], '{"display_columns":[{"name":"user_id","label":"User Id","table_key":"self"},{"name":"item_id","label":"Item Id","table_key":"self"},{"name":"item_summary","label":"Item Summary","table_key":"self"},{"name":"module_name","label":"Module Name","table_key":"self"},{"name":"date_modified","label":"Last Modified","table_key":"self"}],"module":"Trackers","group_defs":[],"summary_columns":[],"report_name":"'.$lang_strings['DEFAULT_REPORT_TITLE_32'].'","chart_type":"none","numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"tabular","full_table_list":{"self":{"value":"Trackers","module":"Trackers","label":"Trackers"},"Trackers:assigned_user_link":{"name":"Trackers  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"Trackers:assigned_user_link"},"dependents":["Filter.1_table_filter_row_4","Filter.1_table_filter_row_5","Filter.1_table_filter_row_4","Filter.1_table_filter_row_4"],"module":"Users","label":"Assigned to User","optional":false},"Trackers:assigned_user_link:reports_to_link":{"name":"Trackers  >  Assigned to User  >  Reports To","parent":"Trackers:assigned_user_link","link_def":{"name":"reports_to_link","relationship_name":"user_direct_reports","bean_is_lhs":false,"link_type":"one","label":"Reports to","table_key":"Trackers:assigned_user_link:reports_to_link"},"dependents":["Filter.1_table_filter_row_5","Filter.1_table_filter_row_4","Filter.1_table_filter_row_4"],"module":"Users","label":"Reports to"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"action","table_key":"self","qualifier_name":"equals","input_name0":"save","input_name1":"on"},"1":{"name":"date_modified","table_key":"self","qualifier_name":"tp_last_30_days","input_name0":"tp_last_30_days","input_name1":"on"},"2":{"name":"module_name","table_key":"self","qualifier_name":"not_equals_str","input_name0":"UserPreferences","input_name1":"on"},"3":{"name":"user_name","table_key":"Trackers:assigned_user_link:reports_to_link","qualifier_name":"is","input_name0":["Current User"]}}}}', 'tabular');
        
    // Active User Sessions (Last 7 Days)
    $default_reports[] = array('TrackerSessions', $lang_strings['DEFAULT_REPORT_TITLE_41'], '{"display_columns":[{"name":"user_name","label":"User Name","table_key":"TrackerSessions:assigned_user_link"},{"name":"first_name","label":"First Name","table_key":"TrackerSessions:assigned_user_link"},{"name":"last_name","label":"Last Name","table_key":"TrackerSessions:assigned_user_link"},{"name":"round_trips","label":"Session Roundtrips","table_key":"self"},{"name":"seconds","label":"Seconds","table_key":"self"}],"module":"TrackerSessions","group_defs":[],"summary_columns":[],"report_name":"' . $lang_strings['DEFAULT_REPORT_TITLE_41'] . '","chart_type":"none","numerical_chart_column":"","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"tabular","full_table_list":{"self":{"value":"TrackerSessions","module":"TrackerSessions","label":"TrackerSessions"},"TrackerSessions:assigned_user_link":{"name":"TrackerSessions  >  Assigned to User","parent":"self","link_def":{"name":"assigned_user_link","relationship_name":"tracker_user_id","bean_is_lhs":false,"link_type":"one","label":"Assigned to User","table_key":"TrackerSessions:assigned_user_link"},"dependents":["display_cols_row_1","display_cols_row_2","display_cols_row_3","display_cols_row_1","display_cols_row_2","display_cols_row_3"],"module":"Users","label":"Assigned to User"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"date_end","table_key":"self","qualifier_name":"tp_last_7_days","input_name0":"tp_last_7_days","input_name1":"on"},"1":{"name":"active","table_key":"self","qualifier_name":"equals","input_name0":["1"]}}}}', 'tabular', 'none');
    
    // User Session Summary (Last 7 Days)
    $default_reports[] = array('TrackerSessions', $lang_strings['DEFAULT_REPORT_TITLE_42'], '{"display_columns":[],"module":"TrackerSessions","group_defs":[{"name":"user_id","label":"User Id","table_key":"self","type":"varchar"}],"summary_columns":[{"name":"user_id","label":"User Id","table_key":"self"},{"name":"count","label":"Count","field_type":"","group_function":"count","table_key":"self"},{"name":"round_trips","label":"SUM: Session Roundtrips","field_type":"int","group_function":"sum","table_key":"self"},{"name":"seconds","label":"SUM: Seconds","field_type":"int","group_function":"sum","table_key":"self"}],"report_name":"'. $lang_strings['DEFAULT_REPORT_TITLE_42'] .'","chart_type":"none","chart_description":"","numerical_chart_column":"self:round_trips:sum","numerical_chart_column_type":"","assigned_user_id":"1","report_type":"summary","full_table_list":{"self":{"value":"TrackerSessions","module":"TrackerSessions","label":"TrackerSessions"}},"filters_def":{"Filter_1":{"operator":"AND","0":{"name":"date_end","table_key":"self","qualifier_name":"tp_last_7_days","input_name0":"tp_last_7_days","input_name1":"on"}}}}', 'summary', 'none');
    
 
    foreach ($default_reports as $report) {
        $saved_report = new SavedReport();
		if ($is_upgrade) {
			$report_id = $saved_report->retrieveReportIdByName($report[1]);
	        if (!empty ($report_id))
	        	continue;
		}
        if ($report[3] == 'tabular') {
        	$result = $saved_report->save_report(-1, 1, $report[1], $report[0], $report[3], $report[2], 1, '1', 'none');
        }
		else {
        	$result = $saved_report->save_report(-1, 1, $report[1], $report[0], $report[3], $report[2], 1, '1', $report[4]);
        }
    }
                                                                                                       
}

?>